<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dinesh Potla">
<meta name="dcterms.date" content="2026-09-07">
<meta name="description" content="An exploratory Michigan FIA detection pilot, benchmark reassessment, and a revised direction toward sapling recruitment.">

<title>Canopy to Cohort</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-5685cd926c25366c96d9f1407e584118.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Canopy to Cohort">
<meta property="og:description" content="An exploratory Michigan FIA detection pilot, benchmark reassessment, and a revised direction toward sapling recruitment.">
<meta property="og:image" content="https://dineshpotla.github.io/canopy-to-cohort/outputs/figures/08_longitudinal_transitions.png">
<meta property="og:site_name" content="Canopy to Cohort">
<meta property="og:image:height" content="1984">
<meta property="og:image:width" content="2688">
<meta name="twitter:title" content="Canopy to Cohort">
<meta name="twitter:description" content="An exploratory Michigan FIA detection pilot, benchmark reassessment, and a revised direction toward sapling recruitment.">
<meta name="twitter:image" content="https://dineshpotla.github.io/canopy-to-cohort/outputs/figures/08_longitudinal_transitions.png">
<meta name="twitter:image-height" content="1984">
<meta name="twitter:image-width" content="2688">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed report-page quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Canopy to Cohort</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/recruitment.html"> 
<span class="menu-text">Recruitment study</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/spatial-context.html"> 
<span class="menu-text">Maps and visuals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../report/index.html" aria-current="page"> 
<span class="menu-text">Detection pilot</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/research-direction.html"> 
<span class="menu-text">Research direction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/analysis-decisions.html"> 
<span class="menu-text">Analysis decisions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/data-dictionary.html"> 
<span class="menu-text">Data dictionary</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dineshpotla/canopy-to-cohort"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Canopy to Cohort</h1>
            <p class="subtitle lead">Detection-transition pilot and its limits as evidence about sugar-maple regeneration</p>
                  <div>
        <div class="description">
          An exploratory Michigan FIA detection pilot, benchmark reassessment, and a revised direction toward sapling recruitment.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://github.com/dineshpotla">Dinesh Potla</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 7, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">In this report</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#why-the-research-direction-changed" id="toc-why-the-research-direction-changed" class="nav-link" data-scroll-target="#why-the-research-direction-changed"><span class="header-section-number">1</span> Why the research direction changed</a></li>
  <li><a href="#questions-addressed-by-this-pilot" id="toc-questions-addressed-by-this-pilot" class="nav-link" data-scroll-target="#questions-addressed-by-this-pilot"><span class="header-section-number">2</span> Questions addressed by this pilot</a></li>
  <li><a href="#data-and-cohort" id="toc-data-and-cohort" class="nav-link" data-scroll-target="#data-and-cohort"><span class="header-section-number">3</span> Data and cohort</a>
  <ul class="collapse">
  <li><a href="#fia-source-and-analytical-grain" id="toc-fia-source-and-analytical-grain" class="nav-link" data-scroll-target="#fia-source-and-analytical-grain"><span class="header-section-number">3.1</span> FIA source and analytical grain</a></li>
  <li><a href="#following-the-same-microplot-footprint" id="toc-following-the-same-microplot-footprint" class="nav-link" data-scroll-target="#following-the-same-microplot-footprint"><span class="header-section-number">3.2</span> Following the same microplot footprint</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">4</span> Methods</a>
  <ul class="collapse">
  <li><a href="#repeated-outcome" id="toc-repeated-outcome" class="nav-link" data-scroll-target="#repeated-outcome"><span class="header-section-number">4.1</span> Repeated outcome</a></li>
  <li><a href="#baseline-predictors" id="toc-baseline-predictors" class="nav-link" data-scroll-target="#baseline-predictors"><span class="header-section-number">4.2</span> Baseline predictors</a></li>
  <li><a href="#model-and-validation" id="toc-model-and-validation" class="nav-link" data-scroll-target="#model-and-validation"><span class="header-section-number">4.3</span> Model and validation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5</span> Results</a>
  <ul class="collapse">
  <li><a href="#four-transition-states" id="toc-four-transition-states" class="nav-link" data-scroll-target="#four-transition-states"><span class="header-section-number">5.1</span> Four transition states</a></li>
  <li><a href="#detection-loss-associations" id="toc-detection-loss-associations" class="nav-link" data-scroll-target="#detection-loss-associations"><span class="header-section-number">5.2</span> Detection-loss associations</a></li>
  <li><a href="#geographic-validation-and-risk-separation" id="toc-geographic-validation-and-risk-separation" class="nav-link" data-scroll-target="#geographic-validation-and-risk-separation"><span class="header-section-number">5.3</span> Geographic validation and risk separation</a></li>
  <li><a href="#reassessment-what-does-the-full-model-add" id="toc-reassessment-what-does-the-full-model-add" class="nav-link" data-scroll-target="#reassessment-what-does-the-full-model-add"><span class="header-section-number">5.4</span> Reassessment: what does the full model add?</a></li>
  <li><a href="#appearance-occurred-but-was-not-forecast-reliably" id="toc-appearance-occurred-but-was-not-forecast-reliably" class="nav-link" data-scroll-target="#appearance-occurred-but-was-not-forecast-reliably"><span class="header-section-number">5.5</span> Appearance occurred, but was not forecast reliably</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">7</span> Limitations</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">8</span> Reproducibility</a></li>
  <li><a href="#next-research-step" id="toc-next-research-step" class="nav-link" data-scroll-target="#next-research-step"><span class="header-section-number">9</span> Next research step</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/report/index.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">






<div class="report-opening column-page">
<div class="report-opening-copy">
<p><span class="report-eyebrow">Michigan · repeated FIA conditions · approximately 5–8 years apart</span></p>
<p><span class="report-deck">Which detections disappear—and can new detections be anticipated?</span></p>
<p>This exploratory pilot follows mapped forest conditions through time. It describes repeated seedling tallies, not recruitment success. The <a href="../report/recruitment.html">recruitment study</a> now implements the revised primary direction with a new endpoint, linked-stem fates, and newly fitted models. This page preserves the supporting detection pilot.</p>
<div class="report-tags">
<p><span class="report-tag">exploratory pilot</span> <span class="report-tag">microplot continuity</span> <span class="report-tag">strong benchmarks</span> <span class="report-tag">county-held-out validation</span></p>
</div>
</div>
<div class="report-cover-figure">
<p><img src="../outputs/figures/08_longitudinal_transitions.png" class="img-fluid" alt="Two stacked bars show follow-up seedling detection for baseline non-detected and detected conditions. Most states persist; 75 of 677 baseline detections become non-detections."></p>
<p><span class="report-cover-caption">The outcome is a repeated tally state, not a claim that individual seedlings were tracked.</span></p>
</div>
</div>
<div class="report-stats column-page">
<div class="report-stat">
<p><span class="report-stat-value"><strong>932</strong></span></p>
<p>strict repeated-condition pairs</p>
</div>
<div class="report-stat">
<p><span class="report-stat-value"><strong>75 / 677</strong></span></p>
<p>baseline detections lost at follow-up</p>
</div>
<div class="report-stat">
<p><span class="report-stat-value"><strong>0.856</strong></span></p>
<p>county-held-out ROC AUC</p>
</div>
<div class="report-stat report-stat-accent">
<p><span class="report-stat-value"><strong>+0.011</strong></span></p>
<p>AUC added over abundance and observation</p>
</div>
</div>
<div class="headline-result column-page">
<p><span class="headline-result-label">Bottom line</span></p>
<p><strong>11.1% of conditions with sugar-maple seedlings detected at baseline had no seedlings tallied at the next visit.</strong> Starting abundance, sampling coverage, and interval already account for 94.2% of the full model’s Brier improvement over prevalence. Added stand variables provide a small, uncertain improvement. The earlier field-triage claim is withdrawn: these results concern detection, not regeneration failure, and do not establish operational value. Beech remains an exploratory association, not the project’s organizing explanation.</p>
</div>
<section id="abstract" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="abstract">Abstract</h2>
<p>This exploratory study links 932 repeated Michigan Forest Inventory and Analysis (FIA) forest conditions with established sugar maple at baseline, accessible sampling at both visits, one-to-one mapping, and comparable microplot footprints. Visits were separated by 5.4–8.1 years. Of 677 baseline seedling detections, 75 became non-detections. County-held-out validation of a seven-slope logistic model gave Brier 0.08151 and AUC 0.856, compared with 0.08253 and 0.845 for starting abundance, coverage, and interval alone. The added predictive improvement is small and uncertain under a paired county bootstrap conditional on existing fitted folds. Sixty of 75 losses began with no more than five tallied seedlings. Among 255 baseline non-detections, 59 became detections; a four-slope appearance model had weak held-out discrimination (AUC 0.566). Neither endpoint measures individual survival or sapling recruitment. The pilot is retained as measurement evidence; the revised primary goal evaluates recruitment and linked sapling fates rather than promoting a detection-risk tool.</p>
</section>
<section id="why-the-research-direction-changed" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="why-the-research-direction-changed"><span class="header-section-number">1</span> Why the research direction changed</h2>
<p>The first project release asked which size classes occurred together at one visit. That work produced an important measurement result: combining 1–4.9-inch saplings with trees at least 5 inches DBH made “maple abundance” look more informative than established-tree abundance alone. Once FIA size classes were separated, sapling presence—not additional established-maple basal area—carried most of the same-visit association.</p>
<p>Repeated conditions improved time ordering, but the detection pilot still leaves the central ecological question unanswered: do observed seedlings lead to advancing regeneration? Presence can persist without advancement, while disappearance from a size class can include growth into a larger class. The current direction review therefore changes the primary endpoint, not merely the model’s complexity.</p>
<p>Michigan studies report abundant small seedlings alongside limited larger regeneration <span class="citation" data-cites="henry2021">(<a href="#ref-henry2021" role="doc-biblioref">Henry et al. 2021</a>)</span>, and show that small-diameter sugar maples can be old, suppressed stems <span class="citation" data-cites="henry2023">(<a href="#ref-henry2023" role="doc-biblioref">Henry and Walters 2023</a>)</span>. Regional FIA studies distinguish favorable small-seedling composition from low sugar-maple sapling abundance <span class="citation" data-cites="harris2026">(<a href="#ref-harris2026" role="doc-biblioref">Harris et al. 2026b</a>)</span>. Browse relationships vary by size class <span class="citation" data-cites="harris2025">(<a href="#ref-harris2025" role="doc-biblioref">Harris et al. 2025</a>)</span>. The Canadian beech association is a candidate hypothesis, with geography, size-class definitions, and relative-abundance measures limiting transfer <span class="citation" data-cites="gauthier2025">(<a href="#ref-gauthier2025" role="doc-biblioref">Gauthier 2025</a>)</span>.</p>
<p>Crucially, prior research already predicts FIA sapling recruitment and compares ordinary seedling counts with six height classes <span class="citation" data-cites="harris2022">(<a href="#ref-harris2022" role="doc-biblioref">Harris et al. 2022</a>)</span>; advance-regeneration prediction after disturbance is also established <span class="citation" data-cites="harris2026disturbance">(<a href="#ref-harris2026disturbance" role="doc-biblioref">Harris et al. 2026a</a>)</span>. A useful contribution here must be a Michigan evaluation of indicator performance and limitations, not a claim that longitudinal FIA forecasting is novel.</p>
</section>
<section id="questions-addressed-by-this-pilot" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="questions-addressed-by-this-pilot"><span class="header-section-number">2</span> Questions addressed by this pilot</h2>
<p>The pilot’s primary question was:</p>
<blockquote class="blockquote">
<p>Among Michigan northern-hardwood conditions with established sugar maple and seedlings detected at baseline, which baseline characteristics predict no seedling detection at the next FIA measurement?</p>
</blockquote>
<p>Four secondary questions keep the interpretation honest:</p>
<ol type="1">
<li>How often do the four detection transitions—persistent non-detection, appearance, loss, and persistence—occur?</li>
<li>Does American beech sapling basal area add information beyond starting seedling density and general stand structure?</li>
<li>Does the risk signal survive when whole counties are withheld during model fitting?</li>
<li>Among baseline non-detections, can a lean model forecast later detection appearance?</li>
</ol>
<p>The estimand is a repeated observation probability. It is not individual seedling survival, recruitment into the sapling class, or a causal effect of competition or management.</p>
</section>
<section id="data-and-cohort" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data-and-cohort"><span class="header-section-number">3</span> Data and cohort</h2>
<section id="fia-source-and-analytical-grain" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="fia-source-and-analytical-grain"><span class="header-section-number">3.1</span> FIA source and analytical grain</h3>
<p>The analysis uses the Michigan SQLite release from the U.S. Forest Service FIA DataMart <span class="citation" data-cites="usfs_datamart">(<a href="#ref-usfs_datamart" role="doc-biblioref">U.S. Forest Service 2026</a>)</span> and pins current evaluation “MICHIGAN 2025: 2019-2025: CURRENT AREA, CURRENT VOLUME” (EVALID 262501; inventory window 2019–2025). Sugar maple resolves from <code>REF_SPECIES</code> to <em>Acer saccharum</em> (SPCD 318), American beech to <em>Fagus grandifolia</em> (SPCD 531), and the baseline northern-hardwood cohort to active forest-type group 800 codes <span class="citation" data-cites="burrill2025fiadb">(<a href="#ref-burrill2025fiadb" role="doc-biblioref"><span class="nocase">Burrill et al.</span> 2025</a>)</span>.</p>
<p>The unit is one linked pair of FIA plot conditions. Control numbers are relational identifiers, not coordinates. Exact FIA plot locations are neither used nor inferred; county identifiers are retained only for grouped validation.</p>
</section>
<section id="following-the-same-microplot-footprint" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="following-the-same-microplot-footprint"><span class="header-section-number">3.2</span> Following the same microplot footprint</h3>
<p><code>SUBP_COND_CHNG_MTRX</code> supplies the authoritative condition linkage. Because seedlings are sampled on microplots, the extraction uses <code>SUBPTYP = 2</code>. Rows are first aggregated to each baseline–follow-up condition pair:</p>
<p><span class="math display">\[
Overlap_{bc} = \frac{1}{4}\sum_{s=1}^{4} SUBPTYP\_PROP\_CHNG_{bcs}.
\]</span></p>
<p>Pair degrees are computed before ecological filters. The primary cohort retains only bidirectional one-to-one links, then requires the overlap divided by both baseline and follow-up <code>MICRPROP_UNADJ</code> to be at least 0.90. Small conditions are therefore not rejected merely because their absolute area share is below 0.90. Among strict links, the minimum observed relative overlap was 0.991.</p>
<p>Baseline eligibility requires a sampled accessible-forest condition in forest-type group 800, positive microplot coverage, and at least one live sugar-maple TREE record with DBH ≥5 inches. Follow-up must be sampled accessible forest with positive microplot coverage. It is not required to remain in group 800 because follow-up classification is post-baseline; 98.2% nevertheless remained in that group.</p>
<div class="cell">
<div id="tbl-longitudinal-flow" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longitudinal-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Longitudinal cohort flow. Pair degrees are evaluated before ecological filtering; the primary model uses the final strict repeated-condition cohort.
</figcaption>
<div aria-describedby="tbl-longitudinal-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 57%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">Pair rows</th>
<th style="text-align: right;">Baseline conditions</th>
<th style="text-align: right;">Physical plots</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Positive microplot condition links in the current evaluation</td>
<td style="text-align: right;">8,454</td>
<td style="text-align: right;">8,003</td>
<td style="text-align: right;">6,209</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baseline sampled northern-hardwood conditions</td>
<td style="text-align: right;">1,401</td>
<td style="text-align: right;">1,325</td>
<td style="text-align: right;">1,264</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baseline conditions with established sugar maple</td>
<td style="text-align: right;">1,093</td>
<td style="text-align: right;">1,034</td>
<td style="text-align: right;">1,006</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bidirectional one-to-one condition mapping</td>
<td style="text-align: right;">941</td>
<td style="text-align: right;">941</td>
<td style="text-align: right;">919</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comparable accessible-forest follow-up</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">913</td>
</tr>
<tr class="even">
<td style="text-align: left;">At least 90% shared microplot footprint and positive interval</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">913</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="methods" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="methods"><span class="header-section-number">4</span> Methods</h2>
<section id="repeated-outcome" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="repeated-outcome"><span class="header-section-number">4.1</span> Repeated outcome</h3>
<p>A sampled condition is detected when its aggregated sugar-maple <code>SEEDLING</code> density is positive. A missing sugar-maple row becomes zero only when <code>MICRPROP_UNADJ &gt; 0</code> demonstrates sampling opportunity. The four transitions are defined independently from baseline and follow-up tallies. The primary binary outcome equals one for baseline detected → follow-up not detected and zero for detected → detected.</p>
<p>“Loss” is shorthand for loss of detection. FIA does not tag individual seedlings, and a zero tally does not demonstrate ecological absence across the forest condition.</p>
</section>
<section id="baseline-predictors" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="baseline-predictors"><span class="header-section-number">4.2</span> Baseline predictors</h3>
<p>All ecological predictors are measured at baseline; interval length is an exposure-time design covariate:</p>
<ul>
<li>baseline sugar-maple seedling density, representing starting abundance;</li>
<li>baseline sugar-maple sapling presence (DBH 1–4.9 inches);</li>
<li>established sugar-maple basal area (DBH ≥5 inches);</li>
<li>American beech sapling basal area (DBH 1–4.9 inches);</li>
<li>non-maple basal area excluding beech saplings, while retaining established beech as background stand structure;</li>
<li>baseline microplot condition coverage, representing detection opportunity; and</li>
<li>elapsed years between measurements.</li>
</ul>
<p>Each basal-area contribution uses the FIA frame on which the tree was sampled. Microplot trees divide by <code>MICRPROP_UNADJ</code>, subplot trees by <code>SUBPPROP_UNADJ</code>, and applicable macroplot trees by <code>MACRPROP_UNADJ</code>. In the current-evaluation cross-sectional audit, the same implementation reproduces FIA <code>COND.BALIVE</code> with mean absolute error 0.000132 ft²/acre across 1,457 conditions.</p>
</section>
<section id="model-and-validation" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="model-and-validation"><span class="header-section-number">4.3</span> Model and validation</h3>
<p>The primary prognostic model is:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{logit}\{P(Loss_c=1)\} =\;&amp; \beta_0
+ \beta_1z\{\log(1 + SeedlingTPA_c)\}
+ \beta_2 SaplingPresent_c \\
&amp;+ \beta_3z\{\log(1 + BA^{est}_{maple,c})\}
+ \beta_4z\{\log(1 + BA^{sap}_{beech,c})\} \\
&amp;+ \beta_5z\{\log(1 + BA_{other,c})\}
+ \beta_6z(Coverage_c)
+ \beta_7z(Interval_c).
\end{aligned}
\]</span></p>
<p>Continuous predictors are standardized within the complete model cohort; every validation fold relearns transformations using training counties only. The 75 losses provide 10.7 events per slope. This accounting ratio does not guarantee adequate sample size or stable prediction; outcome frequency, clustering, complexity, and expected performance also matter <span class="citation" data-cites="riley2020">(<a href="#ref-riley2020" role="doc-biblioref">Riley et al. 2020</a>)</span>. County-cluster CR1 intervals address within-county dependence. A county random-intercept model is retained as sensitivity evidence.</p>
<p>Five deterministic folds hold out entire counties. Reported internal-validation measures are pooled Brier score, ROC AUC, calibration intercept and slope, and Brier skill relative to an intercept-only prevalence benchmark. No county effect or scaling information is transferred to a held-out county.</p>
<p>Nested models separate what each layer contributes: a prevalence benchmark; starting seedling density, coverage, and interval; additional maple stage and stand structure; and finally the American beech sapling hypothesis.</p>
<p>The secondary appearance model is conditioned on no baseline seedling detection. Its four slopes are sugar-maple sapling presence, standardized <code>log1p</code> established-maple basal area, standardized baseline microplot coverage, and standardized interval length. This lean specification represents maple stage continuity, observation opportunity, and exposure time without importing the beech loss hypothesis. The 59 appearances provide 14.75 events per slope overall; the leanest validation training set retains 42 appearances, or 10.5 per slope. It uses the same county-held-out and training-only-scaling protocol as the loss model.</p>
</section>
</section>
<section id="results" class="level2 page-columns page-full" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="results"><span class="header-section-number">5</span> Results</h2>
<section id="four-transition-states" class="level3 page-columns page-full" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="four-transition-states"><span class="header-section-number">5.1</span> Four transition states</h3>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-longitudinal-transitions" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Two stacked bars show 23.1 percent appearance among baseline non-detections and 11.1 percent loss among baseline detections.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-longitudinal-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="../outputs/figures/08_longitudinal_transitions.png" class="img-fluid figure-img column-page" alt="Two stacked bars show 23.1 percent appearance among baseline non-detections and 11.1 percent loss among baseline detections.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-longitudinal-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Sugar-maple seedling detection across repeated FIA conditions. Percentages are conditional on the baseline state.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Among 677 baseline detections, 75 became non-detections and 602 persisted. Among 255 baseline non-detections, 59 (23.1%) became detections. These asymmetric denominators are why loss and appearance are described separately rather than forced into a parameter-heavy multinomial model.</p>
<div class="cell">
<div id="tbl-transitions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Observed transition counts and fractions within each baseline state.
</figcaption>
<div aria-describedby="tbl-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Transition</th>
<th style="text-align: left;">Baseline state</th>
<th style="text-align: right;">Conditions</th>
<th style="text-align: right;">Fraction within baseline state</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Persistent non-detection</td>
<td style="text-align: left;">Not detected</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">76.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Appearance</td>
<td style="text-align: left;">Not detected</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">23.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Loss</td>
<td style="text-align: left;">Detected</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">11.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Persistence</td>
<td style="text-align: left;">Detected</td>
<td style="text-align: right;">602</td>
<td style="text-align: right;">88.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="detection-loss-associations" class="level3 page-columns page-full" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="detection-loss-associations"><span class="header-section-number">5.2</span> Detection-loss associations</h3>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-longitudinal-warning" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="A forest plot shows lower loss odds with greater initial seedling density and sampling coverage, and higher odds with American beech sapling basal area. A bar chart shows loss rising from 0.6 percent in the lowest predicted-risk quartile to 32.5 percent in the highest.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-longitudinal-warning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="../outputs/figures/09_longitudinal_early_warning.png" class="img-fluid figure-img column-page" alt="A forest plot shows lower loss odds with greater initial seedling density and sampling coverage, and higher odds with American beech sapling basal area. A bar chart shows loss rising from 0.6 percent in the lowest predicted-risk quartile to 32.5 percent in the highest.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-longitudinal-warning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Baseline early-warning associations and geographically held-out risk strata. Odds-ratio intervals use county-cluster CR1 uncertainty; risk-quartile predictions come only from models that excluded the condition’s county.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The clearest detection-risk warning was a thin starting cohort. A one-SD increase in transformed baseline seedling density corresponded to OR 0.20 (95% CI 0.14–0.28) for later non-detection. Because the model conditions on a positive baseline tally, this strong association can include regression to the mean and repeated-count variability as well as biological change. Coverage also mattered (OR 0.60, 95% CI 0.49–0.75), consistent with observation opportunity contributing to apparent risk; the association may also reflect ecological differences among condition footprints.</p>
<p>American beech sapling basal area had OR 1.31 (95% CI 1.07–1.62). Adding it to the stage-structure model reduced AIC by 4.09 and improved the nested likelihood-ratio comparison (<em>p</em> = 0.014). In county-held-out validation it modestly improved both Brier score and AUC relative to the stage-structure model. This consistency makes beech a credible follow-up hypothesis, but not a demonstrated mechanism.</p>
<p>Sugar-maple sapling presence was associated with directionally lower loss odds (OR 0.66, 95% CI 0.34–1.29) but imprecisely. Established-maple basal area also had an imprecise association (OR 1.46, 95% CI 0.98–2.18). These intervals do not establish protective effects or their absence.</p>
<div class="cell">
<div id="tbl-longitudinal-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longitudinal-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Primary longitudinal model associations. Continuous effects are per one SD on the transformed scale; intervals use county-cluster CR1 covariance.
</figcaption>
<div aria-describedby="tbl-longitudinal-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 56%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Odds ratio</th>
<th style="text-align: right;">95% CI</th>
<th style="text-align: right;">Robust p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Baseline sugar-maple seedling density</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.14–0.28</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sugar-maple saplings present at baseline</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.34–1.29</td>
<td style="text-align: right;">0.221</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Established sugar-maple basal area</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">0.98–2.18</td>
<td style="text-align: right;">0.061</td>
</tr>
<tr class="even">
<td style="text-align: left;">American beech sapling basal area</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">1.07–1.62</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-maple basal area excluding beech saplings</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">0.82–1.68</td>
<td style="text-align: right;">0.387</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baseline microplot condition coverage</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.49–0.75</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Measurement interval</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">0.88–1.57</td>
<td style="text-align: right;">0.273</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="geographic-validation-and-risk-separation" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="geographic-validation-and-risk-separation"><span class="header-section-number">5.3</span> Geographic validation and risk separation</h3>
<p>The full model achieved held-out Brier score 0.082, AUC 0.856, calibration intercept -0.003, and calibration slope 0.882. Its Brier skill relative to fold-specific prevalence was 17.7%.</p>
<p>The highest predicted-risk quartile contained 55 of all 75 losses and had an observed loss fraction of 32.5%. The lowest quartile had 1 loss (0.6%). Predicted and observed fractions were close in all four quartiles, but these are internal risk strata—not universal intervention thresholds.</p>
<div class="cell">
<div id="tbl-longitudinal-validation" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longitudinal-validation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Five-fold validation with whole counties held out. The prevalence benchmark has no meaningful discrimination or calibration slope.
</figcaption>
<div aria-describedby="tbl-longitudinal-validation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 45%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 23%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Brier</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Calibration slope</th>
<th style="text-align: right;">Brier skill</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Beech hypothesis</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">0.856</td>
<td style="text-align: right;">0.882</td>
<td style="text-align: right;">17.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prevalence benchmark</td>
<td style="text-align: right;">0.099</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stage structure</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.845</td>
<td style="text-align: right;">0.868</td>
<td style="text-align: right;">16.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Starting abundance and observation</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.845</td>
<td style="text-align: right;">0.915</td>
<td style="text-align: right;">16.7%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The county random-intercept sensitivity converged without singularity and estimated county variance 0.178. Its AIC was slightly higher than the fixed-effect model. The small difference does not decisively resolve the grouping specification.</p>
</section>
<section id="reassessment-what-does-the-full-model-add" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="reassessment-what-does-the-full-model-add"><span class="header-section-number">5.4</span> Reassessment: what does the full model add?</h3>
<p>A high AUC is not sufficient evidence of useful ecological prediction. The abundance-and-observation benchmark already achieves AUC 0.845. Relative to that benchmark, the full model’s Brier difference is -0.00102 (95% conditional county-bootstrap interval -0.00585 to 0.00475; negative favors the full model). The AUC difference is 0.011 (interval -0.013 to 0.031). These intervals resample counties in existing held-out predictions without refitting; they omit model-development and fold-selection uncertainty. They do not prove equivalence or rule out useful improvement.</p>
<div class="cell">
<div id="tbl-direction-benchmarks" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-direction-benchmarks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Exploratory benchmark audit on identical held-out observations. Top 169 is a matched comparison capacity, not a management threshold.
</figcaption>
<div aria-describedby="tbl-direction-benchmarks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 56%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Brier</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Losses among top 169</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Starting density only</td>
<td style="text-align: right;">0.08536</td>
<td style="text-align: right;">0.830</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Starting abundance and observation</td>
<td style="text-align: right;">0.08253</td>
<td style="text-align: right;">0.845</td>
<td style="text-align: right;">53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Beech hypothesis</td>
<td style="text-align: right;">0.08151</td>
<td style="text-align: right;">0.856</td>
<td style="text-align: right;">55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maple structure and total nonmaple</td>
<td style="text-align: right;">0.08322</td>
<td style="text-align: right;">0.846</td>
<td style="text-align: right;">53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maple structure and total nonmaple plus beech</td>
<td style="text-align: right;">0.08151</td>
<td style="text-align: right;">0.856</td>
<td style="text-align: right;">55</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At identical capacity, the full model captures 55 losses versus 53 for the strong benchmark. A fair comparator using total non-maple basal area, then adding beech, gives almost the same full-model performance; fixing that comparison does not erase the beech association. Its incremental uncertainty still warrants caution.</p>
<p>Direct source-count reconciliation found 34 losses among 82 conditions starting with one tallied seedling, 26 among 129 starting with two to five, 12 among 183 with six to twenty, and three among 283 with more than twenty. Thus 60 of 75 losses began with five or fewer tallied seedlings. This pattern persists on nearly fully covered conditions. It supports studying sparse-count instability, without establishing how much is biological versus observational.</p>
</section>
<section id="appearance-occurred-but-was-not-forecast-reliably" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="appearance-occurred-but-was-not-forecast-reliably"><span class="header-section-number">5.5</span> Appearance occurred, but was not forecast reliably</h3>
<p>Among the 255 conditions without a baseline detection, 59 (23.1%) had a positive tally at follow-up. This is detection appearance, not proof of new recruitment or establishment.</p>
<p>The full secondary model achieved held-out Brier score 0.179 against 0.180 for the fold-specific prevalence benchmark, AUC 0.566, and calibration slope 0.460. Its Brier skill was only 0.5%. Risk ranking was not monotonic: observed appearance was 32.8% in quartile 3 and 23.8% in quartile 4.</p>
<p>Sugar-maple sapling presence had OR 1.77 (95% county-cluster interval 0.87–3.59), but its interval crossed one. No appearance-model interval excluded one. The tested specification performed weakly in this cohort and partition. That does not establish a predictive limit of all FIA variables or methods, or imply that appearance is ecologically unstructured.</p>
<div class="cell">
<div id="tbl-appearance-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-appearance-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Secondary appearance-model associations among baseline non-detections. Continuous effects are per one SD on the transformed scale; all county-cluster intervals include one.
</figcaption>
<div aria-describedby="tbl-appearance-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 53%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Odds ratio</th>
<th style="text-align: right;">95% CI</th>
<th style="text-align: right;">Robust p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sugar-maple saplings present at baseline</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: right;">0.87–3.59</td>
<td style="text-align: right;">0.112</td>
</tr>
<tr class="even">
<td style="text-align: left;">Established sugar-maple basal area</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.71–1.34</td>
<td style="text-align: right;">0.902</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baseline microplot condition coverage</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.86–1.89</td>
<td style="text-align: right;">0.234</td>
</tr>
<tr class="even">
<td style="text-align: left;">Measurement interval</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.85–1.53</td>
<td style="text-align: right;">0.393</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="discussion" class="level2 page-columns page-full" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="discussion"><span class="header-section-number">6</span> Discussion</h2>
<div class="interpretation-grid column-page">
<div class="interpretation-card interpretation-supported">
<p><span class="interpretation-kicker">What the evidence supports</span></p>
<ul>
<li>Seedling detection is usually persistent, but roughly one in nine baseline detections became a zero tally at the next visit.</li>
<li>Low starting seedling tallies are strongly associated with later zero tallies.</li>
<li>Detection opportunity must remain explicit when interpreting these transitions.</li>
<li>The stand variables add little prediction beyond abundance and observation; beech remains an exploratory association.</li>
<li>County-held-out detection ranking is not evidence of recruitment prediction or management value.</li>
<li>Detection appearance occurred in nearly one quarter of baseline non-detections, but the tested compact model did not forecast it reliably.</li>
</ul>
</div>
<div class="interpretation-card interpretation-boundary">
<p><span class="interpretation-kicker">What it does not establish</span></p>
<ul>
<li>That the original seedlings died or that sugar maple became locally extinct.</li>
<li>That American beech caused the change rather than marking browsing, soils, disturbance history, or other site conditions.</li>
<li>Which management treatment would prevent loss.</li>
<li>Statewide or county prevalence under the formal FIA survey design.</li>
<li>Performance in another state, inventory cycle, or independent field study.</li>
<li>That the appearance model can identify sites likely to gain seedlings.</li>
</ul>
</div>
</div>
<p>The earlier recommendation to use this model for field triage was premature. A triage study would need a regeneration-relevant outcome, a stated survey objective and capacity, and evidence of improvement over a simple abundance rule. The present pilot supplies none of those operational validations. Its useful contribution is to expose the distinction between repeat detection and advancing regeneration.</p>
<p>The beech signal could reflect competitive pressure, deer selectivity, site fertility, sprouting history, or unmeasured management. It is one hypothesis among several, not a prescription or sufficient reason to organize the next study around beech.</p>
</section>
<section id="limitations" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="limitations"><span class="header-section-number">7</span> Limitations</h2>
<ol type="1">
<li><strong>Detection, not tracked survival.</strong> FIA seedlings are tally records, not tagged individuals. A transition to zero can reflect mortality, growth out of the size class, spatial turnover, phenology, or imperfect detection.</li>
<li><strong>Conditioning and repeated counts.</strong> The loss model begins with positive baseline tallies and uses their density as its strongest predictor. Low positive counts are mechanically more likely to become zero under repeated sampling, so this coefficient can reflect regression to the mean or count variability even when latent abundance is stable.</li>
<li><strong>Observation footprint.</strong> Although all primary pairs share at least 90% of both condition footprints—and in practice at least 99.1%—smaller microplot condition shares still provide fewer opportunities to encounter seedlings.</li>
<li><strong>Strict-pair selection.</strong> Split, merged, inaccessible, and nonforest follow-ups are excluded from the primary biological outcome. Nine otherwise eligible strict baseline conditions lacked a comparable follow-up.</li>
<li><strong>Two observations.</strong> One interval identifies a transition but not a trajectory, lag structure, or recruitment rate.</li>
<li><strong>Prognostic coefficients.</strong> Baseline associations do not identify causal effects. Inter-visit treatment was deliberately excluded from the primary model because timing and confounding by indication are inadequate for causal inference.</li>
<li><strong>Unmeasured mechanisms.</strong> Browse, detailed seedling height, soils, invasive plants, and understory vegetation are available only for small nested FIA subsets.</li>
<li><strong>Internal validation.</strong> County-held-out validation tests geographic transport within Michigan, not external generalization. The reassessment reuses these folds; its bootstrap is conditional on fitted predictions. This is exploratory reanalysis, not untouched confirmation.</li>
<li><strong>Weak gain model.</strong> The secondary appearance model has low discrimination and shrinkage-prone calibration. Appearance may depend on unmeasured seed production, microsites, browse, disturbance timing, or count variation; it is not a usable site-level gain forecast.</li>
<li><strong>Survey estimand.</strong> <code>TPA_UNADJ</code> and condition proportions support within-plot density construction; they are not statewide survey weights. Formal prevalence requires FIA population-estimation procedures <span class="citation" data-cites="bechtold2005sampling">(<a href="#ref-bechtold2005sampling" role="doc-biblioref">Bechtold and Patterson 2005</a>)</span>.</li>
</ol>
</section>
<section id="reproducibility" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="reproducibility"><span class="header-section-number">8</span> Reproducibility</h2>
<p>The pipeline records 85 hashed source artifacts, a pinned evaluation, condition-link audits, frame-specific basal-area validation, cohort flow, scaling constants, model support, county-cluster inference, nested model comparisons, fold assignments, held-out predictions for both conditional outcomes, and tests. The mapping audit found zero broken condition references and zero disagreements between matrix predecessor links and <code>PLOT.PREV_PLT_CN</code>.</p>
<p>From a fresh clone:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> setup</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> acquire</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> all</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>longitudinal</code> target runs <code>scripts/09_build_longitudinal_dataset.R</code> and <code>scripts/10_longitudinal_models.R</code>. The <code>direction-audit</code> target runs the benchmark and recruitment-feasibility audits in scripts 11 and 12. Raw, interim, and record-level processed FIA data remain excluded from version control; aggregate evidence and figures contain no plot coordinates.</p>
</section>
<section id="next-research-step" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="next-research-step"><span class="header-section-number">9</span> Next research step</h2>
<p>The <a href="../report/recruitment.html">recruitment study</a> now tests whether ordinary seedling and sapling observations anticipate new sapling recruitment. Its audited cohort contains 922 intervals, 169 new live saplings in 100 conditions, and a companion linked-stem fate analysis. The original 171-stem feasibility screen and 2,308 historical candidate intervals are retained in the direction audit; they are not the final recruitment model population. See the <a href="../docs/research-direction.html">current goals</a> for what is implemented and what remains unresolved.</p>
<p>First validate ingrowth codes, sampling-frame continuity, species corrections, and sampled zero-tree visits. Then compare a small sequence of observation, abundance, and stage-structure models using grouped validation and a retrospective temporal check. Report surviving growth, death, and identity changes separately. RI height classes are a conditional extension if repeated Michigan support proves adequate; any browse predictor needs a circularity check. Negative or imprecise incremental results are valid outcomes of this study.</p>
</section>
<section id="references" class="level2 unnumbered page-columns page-full">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-bechtold2005sampling" class="csl-entry" role="listitem">
Bechtold, William A., and Paul L. Patterson, eds. 2005. <em>The Enhanced Forest Inventory and Analysis Program: National Sampling Design and Estimation Procedures</em>. GTR-SRS-80. U.S. Department of Agriculture, Forest Service. <a href="https://doi.org/10.2737/SRS-GTR-80">https://doi.org/10.2737/SRS-GTR-80</a>.
</div>
<div id="ref-burrill2025fiadb" class="csl-entry" role="listitem">
<span class="nocase">Burrill, Elizabeth A. et al.</span> 2025. <em>The Forest Inventory and Analysis Database: Database Description and User Guide for Phase 2, Version 9.4</em>. U.S. Department of Agriculture, Forest Service. <a href="https://research.fs.usda.gov/understory/forest-inventory-and-analysis-database-user-guide-nfi">https://research.fs.usda.gov/understory/forest-inventory-and-analysis-database-user-guide-nfi</a>.
</div>
<div id="ref-gauthier2025" class="csl-entry" role="listitem">
Gauthier, Martin-Michel. 2025. <span>“Six Decades of Forest Inventory Data Highlight Decline of Sugar Maple (<span class="nocase">Acer saccharum</span>) Sapling Abundance in Eastern Canada.”</span> <em>Ecology and Evolution</em> 15 (5): e71386. <a href="https://doi.org/10.1002/ece3.71386">https://doi.org/10.1002/ece3.71386</a>.
</div>
<div id="ref-harris2025" class="csl-entry" role="listitem">
Harris, Lucas B., Melissa A. Pastore, and Anthony W. D’Amato. 2025. <span>“Effects of Browsing by White-Tailed Deer on Tree Regeneration Vary by Ontogeny and Palatability in Forests of the Northeastern <span>USA</span>.”</span> <em>Forest Ecology and Management</em> 593: 122906. <a href="https://doi.org/10.1016/j.foreco.2025.122906">https://doi.org/10.1016/j.foreco.2025.122906</a>.
</div>
<div id="ref-harris2026disturbance" class="csl-entry" role="listitem">
Harris, Lucas B., Melissa A. Pastore, and Anthony W. D’Amato. 2026a. <span>“Tree Regeneration Following Natural Disturbance and Harvesting Indicates Challenges Maintaining Forest Composition and Tree Species Diversity in Northern <span>USA</span> Forests.”</span> <em>Journal of Applied Ecology</em> 63 (8): e70522. <a href="https://doi.org/10.1111/1365-2664.70522">https://doi.org/10.1111/1365-2664.70522</a>.
</div>
<div id="ref-harris2026" class="csl-entry" role="listitem">
Harris, Lucas B., Melissa A. Pastore, and Anthony W. D’Amato. 2026b. <span>“Tree Regeneration Trends in Forests of the Northeastern <span>USA</span> and Their Implications for Resilience and Restoration.”</span> <em>Ecological Applications</em> 36 (5): e70288. <a href="https://doi.org/10.1002/eap.70288">https://doi.org/10.1002/eap.70288</a>.
</div>
<div id="ref-harris2022" class="csl-entry" role="listitem">
Harris, Lucas B., Christopher W. Woodall, and Anthony W. D’Amato. 2022. <span>“Increasing the Utility of Tree Regeneration Inventories: Linking Seedling Abundance to Sapling Recruitment.”</span> <em>Ecological Indicators</em> 145: 109654. <a href="https://doi.org/10.1016/j.ecolind.2022.109654">https://doi.org/10.1016/j.ecolind.2022.109654</a>.
</div>
<div id="ref-henry2023" class="csl-entry" role="listitem">
Henry, Catherine R., and Michael B. Walters. 2023. <span>“Sugar Maple (<span class="nocase">Acer saccharum</span>) Age Structure Reveals Limited Establishment and Development of Age Cohorts in Response to Selection Management in Northern Hardwood Forests.”</span> <em>Forest Ecology and Management</em> 546: 121356. <a href="https://doi.org/10.1016/j.foreco.2023.121356">https://doi.org/10.1016/j.foreco.2023.121356</a>.
</div>
<div id="ref-henry2021" class="csl-entry" role="listitem">
Henry, Catherine R., Michael B. Walters, Andrew O. Finley, Gary J. Roloff, and Evan J. Farinosi. 2021. <span>“Complex Drivers of Sugar Maple (<span class="nocase">Acer saccharum</span>) Regeneration Reveal Challenges to Long-Term Sustainability of Managed Northern Hardwood Forests.”</span> <em>Forest Ecology and Management</em> 479: 118541. <a href="https://doi.org/10.1016/j.foreco.2020.118541">https://doi.org/10.1016/j.foreco.2020.118541</a>.
</div>
<div id="ref-riley2020" class="csl-entry" role="listitem">
Riley, Richard D., Joie Ensor, Kym I. E. Snell, et al. 2020. <span>“Calculating the Sample Size Required for Developing a Clinical Prediction Model.”</span> <em>BMJ</em> 368: m441. <a href="https://doi.org/10.1136/bmj.m441">https://doi.org/10.1136/bmj.m441</a>.
</div>
<div id="ref-usfs_datamart" class="csl-entry" role="listitem">
U.S. Forest Service. 2026. <em>FIA DataMart</em>. <a href="https://research.fs.usda.gov/products/dataandtools/fia-datamart">https://research.fs.usda.gov/products/dataandtools/fia-datamart</a>.
</div>
</div>
<div class="report-footer column-page">
<p><strong>Canopy to Cohort</strong> · Supporting detection pilot · <a href="../report/recruitment.html">Primary recruitment study</a></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dineshpotla\.github\.io\/canopy-to-cohort\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/report/index.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>