<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Count-versus-length study design – Canopy to Cohort</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-5685cd926c25366c96d9f1407e584118.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Count-versus-length study design – Canopy to Cohort">
<meta property="og:description" content="Sugar-maple recruitment in Michigan FIA: audited sapling entry, linked-stem fates, and held-out comparisons of regeneration indicators.">
<meta property="og:site_name" content="Canopy to Cohort">
<meta name="twitter:title" content="Count-versus-length study design – Canopy to Cohort">
<meta name="twitter:description" content="Sugar-maple recruitment in Michigan FIA: audited sapling entry, linked-stem fates, and held-out comparisons of regeneration indicators.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Canopy to Cohort</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/recruitment.html"> 
<span class="menu-text">Recruitment study</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/spatial-context.html"> 
<span class="menu-text">Map and figures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/analysis-decisions.html"> 
<span class="menu-text">Analysis decisions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/data-dictionary.html"> 
<span class="menu-text">Data dictionary</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dineshpotla/canopy-to-cohort"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-objective" id="toc-research-objective" class="nav-link active" data-scroll-target="#research-objective">Research objective</a></li>
  <li><a href="#local-sampling-opportunities" id="toc-local-sampling-opportunities" class="nav-link" data-scroll-target="#local-sampling-opportunities">Local sampling opportunities</a></li>
  <li><a href="#primary-population-and-endpoint" id="toc-primary-population-and-endpoint" class="nav-link" data-scroll-target="#primary-population-and-endpoint">Primary population and endpoint</a></li>
  <li><a href="#fixed-comparison" id="toc-fixed-comparison" class="nav-link" data-scroll-target="#fixed-comparison">Fixed comparison</a></li>
  <li><a href="#timing-and-the-claim-being-tested" id="toc-timing-and-the-claim-being-tested" class="nav-link" data-scroll-target="#timing-and-the-claim-being-tested">Timing and the claim being tested</a></li>
  <li><a href="#evaluation-and-meaningful-improvement" id="toc-evaluation-and-meaningful-improvement" class="nav-link" data-scroll-target="#evaluation-and-meaningful-improvement">Evaluation and meaningful improvement</a></li>
  <li><a href="#precision-scenarios" id="toc-precision-scenarios" class="nav-link" data-scroll-target="#precision-scenarios">Precision scenarios</a></li>
  <li><a href="#next-stage-decision" id="toc-next-stage-decision" class="nav-link" data-scroll-target="#next-stage-decision">Next-stage decision</a></li>
  <li><a href="#regional-acquisition-status" id="toc-regional-acquisition-status" class="nav-link" data-scroll-target="#regional-acquisition-status">Regional acquisition status</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/report/length-study.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Count-versus-length study design</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="research-objective" class="level2">
<h2 class="anchored" data-anchor-id="research-objective">Research objective</h2>
<p>This optional follow-up design builds on the completed Michigan <a href="../report/recruitment.html">recruitment study</a>. It specifies the additional measurements and evaluation sample needed to assess seedling length. Regional acquisition and external validation are future work.</p>
<p>Determine whether the length distribution of established sugar-maple seedlings improves predictions of recorded sapling entry beyond ordinary seedling counts on the same sampled area. The immediate scientific product is a paired measurement comparison with a credible assessment sample. A survey-ranking tool, a treatment prescription, and a forecast of canopy replacement are different products requiring additional evidence.</p>
<p>The Michigan <a href="../report/ri-audit.html">measurement audit</a> supplies local feasibility evidence: 90 baseline intervals on 87 physical plots contain 14 recruit-bearing conditions. The 71 intervals with ordinary baseline seedling detections contain all 14 events. Taller-seedling presence is associated with subsequent entry, but its added value after accounting for abundance has not been estimated. The current later-year partition supplies only four assessment events.</p>
<p>Regional research already compared ordinary counts with six RI length classes and found that taller seedlings were important predictors. The proposed one-term comparison is therefore a parsimonious regional assessment, not the discovery that height matters or an exact replication of the published boosted tree models. <span class="citation" data-cites="harris2022">(<a href="#ref-harris2022" role="doc-biblioref">Harris et al. 2022</a>)</span></p>
</section>
<section id="local-sampling-opportunities" class="level2">
<h2 class="anchored" data-anchor-id="local-sampling-opportunities">Local sampling opportunities</h2>
<p>The existing Michigan database was screened across baseline RI visits, rather than only the current evaluation cohort. Baselines require a sampled national-design plot, accessible northern-hardwood forest type, positive microplot area, and a live sugar maple at least five inches DBH. The active forest codes are 801, 802, 805, and 809. Successor plot records, measurement dates, and ordinary baseline seedling-record presence then define the following opportunity screen.</p>
<div class="cell">
<div id="tbl-length-opportunities" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-length-opportunities-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: RI record and visit-date opportunities in the existing Michigan snapshot. These are not validated recruitment intervals or event counts. The final row is a separate branch.
</figcaption>
<div aria-describedby="tbl-length-opportunities-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 61%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Screen</th>
<th style="text-align: right;">Condition visits</th>
<th style="text-align: right;">Physical plots</th>
<th style="text-align: right;">Counties</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Baseline RI record, sampled northern hardwoods, established maple</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exactly one linked successor plot visit</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Successor plot sampled under national design</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recorded interval 4.5-8.5 years</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Also a positive ordinary baseline maple seedling record</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Positive-count opportunities outside current 903-plot cohort</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Separate branch: no linked successor in this snapshot</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">35</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>There are 234 qualifying baseline condition visits on 116 physical plots. Of those, 128 have exactly one linked successor; 114 also have a sampled national-design successor and a recorded interval of 4.5-8.5 years. Requiring a positive ordinary seedling record leaves 88 opportunities on 79 plots.</p>
<p>Those 88 comprise 71 already included in the current RI cohort, ten additional condition visits on plots represented in the current recruitment cohort, and seven visits on six plots outside that cohort. Physical-plot counts cannot be added across these groups because a plot can supply several historical visits. This is a small potential extension, not a new independent evaluation sample.</p>
<p>The screen does not establish RI microplot status, source/count validity, condition continuity, shared-area eligibility, or sapling-entry events for the additional visits. It queries no new recruitment outcomes. The wider historical Michigan source is not an untouched validation sample; unused rows or predictors do not make it one. The 106 baseline condition visits without a linked successor are unresolved opportunities in this snapshot, not guaranteed future observations or a scheduled data release.</p>
<p>As of September 9, 2026, the official Michigan update history lists addition of the 2025 evaluation on April 27, followed by soil and down-wood table updates. It does not identify a newer recruitment inventory cycle. This is release-note evidence, not a bytewise comparison of a freshly downloaded database; refreshing the file cannot be assumed to create an independent cohort. <span class="citation" data-cites="fiaupdates2026mi">(<a href="#ref-fiaupdates2026mi" role="doc-biblioref">U.S. Forest Service 2026</a>)</span></p>
</section>
<section id="primary-population-and-endpoint" class="level2">
<h2 class="anchored" data-anchor-id="primary-population-and-endpoint">Primary population and endpoint</h2>
<p>The primary comparison is among conditions with ordinary baseline sugar-maple seedlings, not the easier mixture of detected and undetected seedlings. Retain the northern-hardwood/adult-maple scope and verified common sampling opportunity from the recruitment study. A regional extension must use harmonized definitions and report each geography separately; a result outside Michigan is a transport assessment, not independent validation of Michigan-specific performance.</p>
<p>The outcome remains at least one new live sugar-maple sapling recorded at the next visit: species 318, live status, diameter at least one and below five inches, reconciliation code 1, no predecessor TREE identifier, and the audited common microplot frame. It excludes ambiguous procedure changes and missed-tree tallies. It is not an individual seedling conversion rate: intervening entrants that die before remeasurement are not observed.</p>
<p>Apply the existing baseline RI frame and count checks before assigning any tally zero. Preserve invalid or inaccessible observations as unavailable. Historical manual access remains qualified, including the 2016 archived draft and the unrecovered 2012-2015 annual supplements. A broader cohort needs its own year-specific review rather than inheriting blanket approval from the 90 cases.</p>
</section>
<section id="fixed-comparison" class="level2">
<h2 class="anchored" data-anchor-id="fixed-comparison">Fixed comparison</h2>
<p>Let N denote the ordinary baseline maple count, H the RI count in classes 5-6 (at least five feet long), A the sampled microplot coverage, and T the elapsed interval. The proposed length feature is Q = H/N. It is undefined when N is zero; those conditions are outside the primary comparison, not assigned Q = 0.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Count model</th>
<th>Count-plus-length model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Abundance</td>
<td>log(1 + N)</td>
<td>log(1 + N)</td>
</tr>
<tr class="even">
<td>Sampling opportunity</td>
<td>A</td>
<td>A</td>
</tr>
<tr class="odd">
<td>Recorded timing</td>
<td>T</td>
<td>T</td>
</tr>
<tr class="even">
<td>Length structure</td>
<td>None</td>
<td>Q = H/N</td>
</tr>
<tr class="odd">
<td>Model family</td>
<td>Ridge logistic regression</td>
<td>Same</td>
</tr>
<tr class="even">
<td>Penalty</td>
<td>1 on standardized slopes; intercept unpenalized</td>
<td>Same</td>
</tr>
<tr class="odd">
<td>Non-intercept terms</td>
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>
<p>Both models use identical cases and development-only standardization. Do not add beech, browse score, six separate classes, interactions, alternative cutoffs, or a favorable model family after inspecting evaluation results. This choice limits the question to one candidate length representation; a negative result would not prove that no length-based method could help.</p>
<p>A required, predeclared sensitivity replaces the single log-count slope with a three-degree-of-freedom natural spline of log(1 + N) in both models, while retaining A, T, and the same single Q addition. Set knots and boundary knots from development data only, standardize the resulting basis there, and use the same fixed ridge penalty. This gives five versus six slopes and must be included in development-support planning. Report it alongside the primary linear-log-count comparison, not as a replacement chosen after seeing results. If the length gain disappears against flexible counts, limit the conclusion to the original model forms; do not claim established added measurement value.</p>
<p>Ordinary counts must be reconciled with RI classes 3-6 on the same sampled area. Unresolved differences stop the comparison before fitting: silently retaining only agreements could create a selected sample. RI seedlings below one foot are excluded from N and Q. Their potential information is a separate question and is not mixed into this one-term length comparison.</p>
<p>For each physical plot, choose the latest completed eligible visit interval within the declared development or assessment period using dates and protocol eligibility, not outcome values. Retain eligible conditions from that interval. Keep every visit and condition of a physical plot on the same side of the development/assessment boundary. Give each plot total training weight one, divided across its included conditions. Freeze this interval-selection and weighting rule before any new outcome comparison.</p>
</section>
<section id="timing-and-the-claim-being-tested" class="level2">
<h2 class="anchored" data-anchor-id="timing-and-the-claim-being-tested">Timing and the claim being tested</h2>
<p>The primary estimand is a retrospective next-visit probability comparison conditional on the realized interval within 4.5-8.5 years. Realized T is shared by both models, so the comparison can test added length information after adjusting for observation duration. However, the actual next-visit date is not known at baseline. This estimand is not an operational forecast made at baseline.</p>
<p>A future forecast must instead specify a genuinely planned horizon and collect or identify outcomes at that horizon. Merely setting T = 7 when scoring existing variable-duration outcomes does not validate seven-year risks. There is no observed exact crossing date from which to reconstruct an exact seven-year recruitment event. The current study should retain the narrower conditional claim until suitable timing evidence exists.</p>
</section>
<section id="evaluation-and-meaningful-improvement" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-and-meaningful-improvement">Evaluation and meaningful improvement</h2>
<p>The primary metric is paired Brier gain: count-model squared probability error minus length-model squared error. Average the condition-level differences within each physical plot, then average across plots:</p>
<p><span class="math display">\[
D_j = \frac{1}{m_j}\sum_{i=1}^{m_j}
\left[(y_{ij}-p_{0,ij})^2-(y_{ij}-p_{1,ij})^2\right],
\qquad \Delta = \frac{1}{J}\sum_{j=1}^{J}D_j.
\]</span></p>
<p>Positive gain favors length. Equal plot weighting prevents plots with more conditions from automatically dominating the evaluation. It differs from a condition-average estimator, which must not be substituted as the benchmark. This is a selected-cohort comparison, not a statewide design-weighted estimate of forest condition.</p>
<p>Evaluate the frozen models once on the reserved sample. Resample whole counties for paired uncertainty, retaining all selected plot/condition records within each county. Such evaluation intervals are conditional on the frozen training fits; they do not include every source of model-development uncertainty. Report geographic event support, calibration curves/intercept/slope, and discrimination alongside Brier gain. With too few independent county clusters, a nominal bootstrap interval is not a sufficient precision guarantee.</p>
<p>A lower confidence limit above zero supports a statistical improvement for these models and this target. To claim a <em>meaningful</em> improvement, first declare a minimum gain delta and require the lower limit to exceed it. An interval spanning zero is inconclusive, not proof of equivalence. Neither an arbitrary Brier threshold nor a small P value supplies field utility. The necessary measurement costs and error consequences remain unspecified.</p>
</section>
<section id="precision-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="precision-scenarios">Precision scenarios</h2>
<p>External-assessment sample sizes depend on the target population, anticipated predictions, calibration, and desired precision; an event-count rule alone cannot establish adequacy. The published guidance concerns clinical models; its design principles transfer, but its clinical thresholds and numerical examples are not forestry sample-size recommendations. <span class="citation" data-cites="riley2024validation">(<a href="#ref-riley2024validation" role="doc-biblioref">Riley et al. 2024</a>)</span></p>
<p>The following calculation is a transparent planning approximation for the mean of frozen plot-level paired losses. With assumed SD s, variance inflation V, and target 95% interval half-width h, use</p>
<p><span class="math display">\[
J_{\mathrm{complete}} = \left\lceil V(1.96s/h)^2\right\rceil.
\]</span></p>
<p>The implementation uses the exact normal quantile rather than rounded 1.96. Candidate plot numbers are complete plots divided by an assumed retention fraction, rounded upward. This scales expected yield; it does not guarantee the required number will be retained, remove attrition bias, or certify power.</p>
<div class="cell">
<div id="tbl-length-precision" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-length-precision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Hypothetical evaluation precision: half-width 0.01 Brier units, variance inflation 1.5, and 80% retention. No SD or inflation factor was estimated from a fitted RI model.
</figcaption>
<div aria-describedby="tbl-length-precision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 34%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Assumed plot-loss SD</th>
<th style="text-align: right;">Complete evaluation plots</th>
<th style="text-align: right;">Candidates at 80% retention</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">145</td>
<td style="text-align: right;">182</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">577</td>
<td style="text-align: right;">722</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">2305</td>
<td style="text-align: right;">2882</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>For the middle SD assumption, this gives 577 complete evaluation plots and 722 candidates at 80% retention. The range is 145-2,305 complete plots across the three SD assumptions. These are not estimates of the number available in any state, not training sample sizes, and not proof of calibration precision. The <a href="../outputs/tables/recruitment-length-paired-precision.csv">full scenario table</a> varies h, V, retention, and s. A smaller target gain typically demands greater precision; h itself is not a minimum useful gain.</p>
<p>A separate fixed-rule illustration asks how many independent event units would give a Wilson interval of a chosen width at an assumed recall. It uses the score-interval formula documented by NIST. <span class="citation" data-cites="nistwilson">(<a href="#ref-nistwilson" role="doc-biblioref">NIST/SEMATECH, n.d.</a>)</span></p>
<div class="cell">
<div id="tbl-length-recall" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-length-recall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Fixed-rule recall illustration. Widths are evaluated at an assumed proportion, not guaranteed or expected widths; these are event units, not total plots.
</figcaption>
<div aria-describedby="tbl-length-recall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assumed recall</th>
<th style="text-align: left;">Target half total width</th>
<th style="text-align: right;">Independent event units</th>
<th style="text-align: left;">Plug-in interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">50%</td>
<td style="text-align: left;">5%</td>
<td style="text-align: right;">381</td>
<td style="text-align: left;">45.0% to 55.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">80%</td>
<td style="text-align: left;">5%</td>
<td style="text-align: right;">245</td>
<td style="text-align: left;">74.5% to 84.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">50%</td>
<td style="text-align: left;">10%</td>
<td style="text-align: right;">93</td>
<td style="text-align: left;">40.0% to 60.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">80%</td>
<td style="text-align: left;">10%</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">68.2% to 88.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At assumed 80% recall, the half-total-width targets 0.10 and 0.05 require 60 and 245 independent event units, respectively. Wilson intervals are not symmetric around the assumed proportion. These are not calculations for a paired gain in recall, a data-selected capacity rule, or dependent conditions on the same plot. They illustrate why four or fourteen events do not settle a forecasting claim.</p>
<p>Before recruitment or model fitting, replace the planning inputs with defensible development and external-assessment ranges, assess training complexity and calibration precision separately, and simulate the proposed cluster structure. Do not add the planning sample counts together or automatically treat their maximum as a fully justified study size: they address different quantities and assumptions.</p>
</section>
<section id="next-stage-decision" class="level2">
<h2 class="anchored" data-anchor-id="next-stage-decision">Next-stage decision</h2>
<p>The local opportunity census does not reveal a sufficiently large independent Michigan assessment cohort. More historical Michigan rows may inform development or sensitivity analysis after full eligibility checks, but do not solve that evaluation problem. Two distinct research routes remain:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Route</th>
<th>Contribution and boundary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Michigan-only</td>
<td>Complete the measurement paper now; reserve genuinely new, adequately supported observations for a future conditional or planned-horizon assessment. A database refresh must be checked for new visits and plot overlap.</td>
</tr>
<tr class="even">
<td>Regional extension</td>
<td>Screen Wisconsin and Minnesota as candidate Great Lakes sources under the same definitions, then fix development and geographically separate evaluation roles from protocol/metadata support before outcome-driven model selection. This changes the target geography and tests transport, not Michigan-specific validation.</td>
</tr>
</tbody>
</table>
<p>The recommended next action is a scoped regional <strong>feasibility screen</strong>, not immediate model fitting. Neither state’s usable RI sample or event support has been established here. The official DataMart is the acquisition route; files must be pinned with source dates and hashes, with measurement inventories separated from evaluation-outcome access. <span class="citation" data-cites="fiadatamart">(<a href="#ref-fiadatamart" role="doc-biblioref">U.S. Forest Service 2025</a>)</span></p>
<p>Proceed to fitting only after source/geography approval, a documented eligible cohort, a declared assessment set, separate development/evaluation precision work, and a frozen analysis specification. If support is insufficient, retain the descriptive study. Changing the population or adding predictors solely to obtain a favorable result would not complete this research objective.</p>
</section>
<section id="regional-acquisition-status" class="level2">
<h2 class="anchored" data-anchor-id="regional-acquisition-status">Regional acquisition status</h2>
<p>The regional feasibility screen covers Wisconsin and Minnesota under the same scientific definitions. Acquisition was attempted, but neither ZIP could be retrieved: the archive endpoints return an empty response in repeated HTTP checks, and the DataMart landing page also fails in the browser. <strong>Regional sample size and validation feasibility remain unknown.</strong> This is an access blocker, not evidence of inadequate samples.</p>
<p>The separate live update-history service lists addition of the 2025 inventories on May 4 for Wisconsin and May 11 for Minnesota, followed by soil-laboratory updates on July 6. Those release notes do not establish usable RI/repeat-visit support or the contents of a retrieved archive. <a href="https://apps.fs.usda.gov/fiadb-api/fiadb_update_history?statecd=55">Wisconsin history</a>, <a href="https://apps.fs.usda.gov/fiadb-api/fiadb_update_history?statecd=27">Minnesota history</a>.</p>
<p>The <a href="../outputs/audits/recruitment-regional-acquisition.csv">acquisition audit</a> records failed transfers with missing sizes and hashes, not zero observations. <code>make regional-acquire</code> provides the bounded retry and source-pinning step; it is intentionally separate from the Michigan pipeline. A successful transfer must pass archive, state, table, integrity, and disk-space guards. The success path is not yet exercised on the actual regional archives.</p>
<p>The <a href="../docs/survey-validation-plan.html">survey validation plan</a> keeps regional feasibility separate from the Michigan outcome analysis. Archive access remains blocked, so no additional model, outcome comparison, or regional validation result is supplied here.</p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p><code>make length-plan</code> regenerates the metadata and hypothetical precision tables. The helpers also implement the defined length fraction and plot-balanced paired score for future use; they have not scored a new RI model. Record-level metadata remain local and Git-ignored. No additional inventory was downloaded and no model was fitted for this design.</p>
<p>The <a href="../docs/survey-validation-plan.html">survey validation plan</a> and <a href="../docs/analysis-decisions.html">analysis decisions</a> retain the scientific and operational boundaries.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-harris2022" class="csl-entry" role="listitem">
Harris, Lucas B., Christopher W. Woodall, and Anthony W. D’Amato. 2022. <span>“Increasing the Utility of Tree Regeneration Inventories: Linking Seedling Abundance to Sapling Recruitment.”</span> <em>Ecological Indicators</em> 145: 109654. <a href="https://doi.org/10.1016/j.ecolind.2022.109654">https://doi.org/10.1016/j.ecolind.2022.109654</a>.
</div>
<div id="ref-nistwilson" class="csl-entry" role="listitem">
NIST/SEMATECH. n.d. <span>“7.2.4.1. Confidence Intervals.”</span> Accessed September 9, 2026. <a href="https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm">https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm</a>.
</div>
<div id="ref-riley2024validation" class="csl-entry" role="listitem">
Riley, Richard D., Kym I. E. Snell, Lucinda Archer, et al. 2024. <span>“Evaluation of Clinical Prediction Models (Part 3): Calculating the Sample Size Required for an External Validation Study.”</span> <em>BMJ</em> 384: e074821. <a href="https://doi.org/10.1136/bmj-2023-074821">https://doi.org/10.1136/bmj-2023-074821</a>.
</div>
<div id="ref-fiadatamart" class="csl-entry" role="listitem">
U.S. Forest Service. 2025. <span>“<span>FIA DataMart</span>.”</span> <a href="https://research.fs.usda.gov/products/dataandtools/fia-datamart">https://research.fs.usda.gov/products/dataandtools/fia-datamart</a>.
</div>
<div id="ref-fiaupdates2026mi" class="csl-entry" role="listitem">
U.S. Forest Service. 2026. <span>“<span>FIADB</span> Update History: Michigan.”</span> <a href="https://apps.fs.usda.gov/fiadb-api/fiadb_update_history?statecd=26">https://apps.fs.usda.gov/fiadb-api/fiadb_update_history?statecd=26</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dineshpotla\.github\.io\/canopy-to-cohort\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/report/length-study.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>