<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-09">

<title>Research direction and goals – Canopy to Cohort</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-5685cd926c25366c96d9f1407e584118.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Research direction and goals – Canopy to Cohort">
<meta property="og:description" content="Sugar-maple recruitment in Michigan FIA: audited sapling entry, linked-stem fates, and held-out comparisons of regeneration indicators.">
<meta property="og:site_name" content="Canopy to Cohort">
<meta name="twitter:title" content="Research direction and goals – Canopy to Cohort">
<meta name="twitter:description" content="Sugar-maple recruitment in Michigan FIA: audited sapling entry, linked-stem fates, and held-out comparisons of regeneration indicators.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Canopy to Cohort</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/recruitment.html"> 
<span class="menu-text">Recruitment study</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../report/index.html"> 
<span class="menu-text">Detection pilot</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../docs/research-direction.html" aria-current="page"> 
<span class="menu-text">Research direction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/analysis-decisions.html"> 
<span class="menu-text">Analysis decisions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../docs/data-dictionary.html"> 
<span class="menu-text">Data dictionary</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dineshpotla/canopy-to-cohort"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#decision" id="toc-decision" class="nav-link active" data-scroll-target="#decision">Decision</a></li>
  <li><a href="#results-after-implementing-the-pivot" id="toc-results-after-implementing-the-pivot" class="nav-link" data-scroll-target="#results-after-implementing-the-pivot">Results after implementing the pivot</a></li>
  <li><a href="#secondary-survey-comparison-and-optional-next-goal" id="toc-secondary-survey-comparison-and-optional-next-goal" class="nav-link" data-scroll-target="#secondary-survey-comparison-and-optional-next-goal">Secondary survey comparison and optional next goal</a></li>
  <li><a href="#count-versus-length-design" id="toc-count-versus-length-design" class="nav-link" data-scroll-target="#count-versus-length-design">Count-versus-length design</a></li>
  <li><a href="#why-the-previous-direction-needs-revision" id="toc-why-the-previous-direction-needs-revision" class="nav-link" data-scroll-target="#why-the-previous-direction-needs-revision">Why the previous direction needs revision</a></li>
  <li><a href="#what-the-relevant-research-actually-supports" id="toc-what-the-relevant-research-actually-supports" class="nav-link" data-scroll-target="#what-the-relevant-research-actually-supports">What the relevant research actually supports</a></li>
  <li><a href="#initial-feasibility-screen-before-the-endpoint-audit" id="toc-initial-feasibility-screen-before-the-endpoint-audit" class="nav-link" data-scroll-target="#initial-feasibility-screen-before-the-endpoint-audit">Initial feasibility screen, before the endpoint audit</a></li>
  <li><a href="#questions-and-completion-criteria" id="toc-questions-and-completion-criteria" class="nav-link" data-scroll-target="#questions-and-completion-criteria">Questions and completion criteria</a></li>
  <li><a href="#scope-and-stopping-rules" id="toc-scope-and-stopping-rules" class="nav-link" data-scroll-target="#scope-and-stopping-rules">Scope and stopping rules</a></li>
  <li><a href="#status-and-reproducibility" id="toc-status-and-reproducibility" class="nav-link" data-scroll-target="#status-and-reproducibility">Status and reproducibility</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/docs/research-direction.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Research direction and goals</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="decision" class="level2">
<h2 class="anchored" data-anchor-id="decision">Decision</h2>
<p>The bounded Michigan core research is complete as of September 9, 2026. The <a href="../report/recruitment.html">revised paper</a> answers the count-information, incremental-stage, and linked-fate questions. Regional data acquisition and length-model validation are deferred optional extensions, not prerequisites for completing this paper. The results do not justify another pivot merely because added-model improvements are small or uncertain.</p>
<p>Change the primary question to <strong>whether observed sugar-maple regeneration leads to recorded recruitment into the sapling size class</strong>. Retain the existing seedling-detection analysis as an exploratory measurement study. Its numerical results remain useful, but the earlier claim that it establishes a field-triage tool is withdrawn.</p>
<p>The project’s goal is:</p>
<blockquote class="blockquote">
<p>Determine how well ordinary FIA seedling and sapling observations anticipate new sugar-maple sapling recruitment in Michigan northern hardwoods, measure what additional stand information contributes, and distinguish recruitment, survival, growth, and observation changes.</p>
</blockquote>
<p>The intended contribution is a transparent Michigan evaluation of regeneration indicators. Its novelty must come from a useful comparison and credible validation. Linking repeated FIA visits or fitting a prediction model is already established in the literature.</p>
<p>The direction decision was made on September 7. The first recruitment analysis was implemented on September 8; its results are summarized below and in the <a href="../report/recruitment.html">recruitment report</a>. The existing data have been explored; this is not a preregistration or external validation.</p>
</section>
<section id="results-after-implementing-the-pivot" class="level2">
<h2 class="anchored" data-anchor-id="results-after-implementing-the-pivot">Results after implementing the pivot</h2>
<p>The final audited recruitment cohort has 922 condition intervals on 903 physical plots across 66 counties. It contains 169 qualifying new live maple saplings in 100 conditions. Nine source pairs fail the conservative shared-frame proportion check and one contains ambiguous new sapling records. The preliminary feasibility counts later in this document are preserved as the earlier screen, not final results.</p>
<p>Seedling count plus coverage and interval has county-held-out AUC 0.796 overall and 0.699 among 672 baseline-detected conditions. Adding existing maple sapling density and established-maple basal area yields AUC 0.806 and 0.711, respectively. The paired Brier improvements are about 0.0016 in both populations, with full-refit county-bootstrap intervals spanning zero. At equal top-quarter capacity the stage model captures fewer recruit-bearing conditions than the count benchmark. These findings do not support organizing the project around added model complexity.</p>
<p>Counts nevertheless contain information. Of 280 conditions with more than twenty recorded baseline seedlings, 72 have a qualifying new sapling at follow-up. Abundant seedlings therefore do not guarantee recorded entry, but the remaining 208 conditions cannot be labeled biological failures from these observations. The companion fate audit separates 334 recorded deaths, 1,188 surviving saplings, and 58 live stems advancing beyond the sapling class among 1,580 comparable stems.</p>
<p>The central contribution is now an implemented measurement-and-prediction study: <strong>what standard regeneration counts tell us, what maple stage variables add, and what neither observation establishes about successful cohort replacement.</strong> Continue with a defined decision and external assessment if operational use is the goal. Do not pivot again merely because incremental effects are modest.</p>
</section>
<section id="secondary-survey-comparison-and-optional-next-goal" class="level2">
<h2 class="anchored" data-anchor-id="secondary-survey-comparison-and-optional-next-goal">Secondary survey comparison and optional next goal</h2>
<p>An explicit, retrospective priority comparison is now implemented. Its main target is no recorded entry among the 672 baseline-detected conditions, at a fixed 25% capacity. Expected target capture is 143 for random selection, 162 for low raw counts, 160 for the count model, and 163 for the stage model. Stage minus raw-count yield is +0.60 percentage points (95% full-refit county interval −3.66 to +2.28). This is not a demonstrated practical improvement. The later-year test gives 65.18 expected targets for raw counts versus 65 for either model, among 68 selected conditions.</p>
<p>The extension also tests the opposite objective, fixed 10%/50% capacities, cutoff-tie uncertainty, and a common seven-year scoring horizon. No-entry remains a record-based proxy, not an independent finding that a site needs surveying. Actual field costs and useful survey outcomes remain unmeasured.</p>
<p>The measurement audit has sharpened an optional follow-on hypothesis:</p>
<blockquote class="blockquote">
<p>Determine whether baseline seedling length structure adds useful recruitment information beyond ordinary counts on the same sampled area, evaluated on a separate and adequately supported sample.</p>
</blockquote>
<p>The <a href="../report/ri-audit.html">RI audit</a> retains 90 baseline condition intervals, 14 events, and 311 sampled microplot-condition intervals. Ordinary maple counts exactly equal the sum of RI classes at least one foot long on every matched unit; length distribution, not the collapsed total, is the candidate extra information. Thirteen of the fourteen events occur in the 44 conditions with baseline maple seedlings at least five feet long, versus one event in 46 conditions without them. This is not an adjusted or held-out count-versus-length comparison.</p>
<p>No height-class model is fitted. The later-year split would leave ten development events and four assessment events. Historical annual supplements were inspected for 2016-2018 (37 intervals, four events), including an archived 2016 draft, but not individually recovered for 2012-2015. The baseline measurement audit is complete with those qualifications; independent forecasting usefulness is not established.</p>
<p>The <a href="../docs/survey-validation-plan.html">survey validation plan</a> records this milestone, the next matched comparison, and the independent decision evidence required before an operational claim. Earlier Wisconsin/Minnesota acquisition was authorized, but that extension is now deferred to prioritize the core paper. Broader extensions and fieldwork remain separate scope decisions.</p>
</section>
<section id="count-versus-length-design" class="level2">
<h2 class="anchored" data-anchor-id="count-versus-length-design">Count-versus-length design</h2>
<p>The optional comparison is specified in the <a href="../report/length-study.html">study design</a>: ordinary count, sampling coverage, and elapsed interval versus the same model plus the fraction of standard-size seedlings at least five feet long. The primary population has ordinary seedlings detected, and the primary metric is plot-balanced paired Brier gain. This is a conditional next-visit comparison, not a validated baseline forecast at an exact seven-year horizon.</p>
<p>The metadata-only historical screen finds 88 positive-seedling opportunities on 79 physical plots, before full RI/condition/endpoint checks. Only seven visits on six plots are outside the current 903-plot recruitment cohort. No new recruitment outcomes were extracted. That small extension does not supply an independent Michigan evaluation set.</p>
<p>The protocol includes hypothetical precision scenarios and a gate requiring a minimum meaningful gain before evaluation; it does not invent field costs or claim that one sample-size rule suffices. The user has authorized the Wisconsin/Minnesota feasibility screen under the same definitions. Such an extension would assess regional transport, not validate Michigan-specific performance. Both archive downloads currently fail with empty responses, so no new state inventory was acquired and regional sample support remains unknown. The <a href="../research/runs/recruitment-2026-09-08/regional-access-review.md">access review</a> records the blocker and reproducible retry step.</p>
</section>
<section id="why-the-previous-direction-needs-revision" class="level2">
<h2 class="anchored" data-anchor-id="why-the-previous-direction-needs-revision">Why the previous direction needs revision</h2>
<ol type="1">
<li><strong>The outcome was too far from the ecological problem.</strong> A positive seedling tally becoming zero measures a change in a sampled size class. It can reflect mortality, sampling variation, or growth out of that class. Continued seedling presence can coexist with little recruitment into larger trees. The pilot therefore does not directly establish regeneration failure or recovery.</li>
<li><strong>Most prediction gain was already available from a simple benchmark.</strong> In the existing county-held-out results, density + coverage + interval achieved AUC 0.8447 and Brier 0.08253. The full seven-slope model achieved 0.8557 and 0.08151. The simpler benchmark accounts for 94.2% of the full model’s Brier improvement over prevalence. Added stand variables reduced benchmark Brier by only 1.24%. Whether that difference is useful requires uncertainty and a defined decision, not just the headline AUC. A paired county bootstrap of existing held-out predictions gives a Brier difference of −0.00102 with a 95% interval of −0.00585 to +0.00475 (negative favors the full model). This conditional interval includes zero; it does not prove equivalence. At equal capacity of 169 conditions, the full model captures 55 losses versus 53 for the strong benchmark. Sixty of 75 losses began with five or fewer tallied seedlings, directly reconciled against <code>SEEDLING.TREECOUNT</code>.</li>
<li><strong>The beech story was promoted too early.</strong> A conditional association is worth investigating, but its modest incremental prediction does not establish an actionable mechanism. The old stage comparator excludes beech sapling basal area from its competitor total. A fair species-specific check also needs a model with total non-maple basal area, then asks what beech adds. That audit leaves full-model performance almost unchanged: it does not erase the beech association, but incremental uncertainty remains substantial.</li>
<li><strong>A weak small model does not establish a limit of the whole database.</strong> The four-term appearance model performed poorly. That result concerns the tested model, cohort, and validation partition; it does not show that no FIA-based method can predict new detections.</li>
<li><strong>Passing software checks did not settle the research question.</strong> Ten events per slope is a rough accounting statistic, not a guarantee of reliable prediction. Sample-size planning also depends on outcome frequency, candidate complexity, clustering, and expected model performance. See <a href="https://doi.org/10.1136/bmj.m441">Riley et al.&nbsp;(2020)</a>. Tests should reproduce calculations; they should not require the appearance model to remain weak.</li>
</ol>
</section>
<section id="what-the-relevant-research-actually-supports" class="level2">
<h2 class="anchored" data-anchor-id="what-the-relevant-research-actually-supports">What the relevant research actually supports</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Primary source</th>
<th>Consequence for this project</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://doi.org/10.1016/j.foreco.2020.118541">Henry et al.&nbsp;(2021), Michigan regeneration</a></td>
<td>Small seedlings can be plentiful while larger regeneration is scarce. Study advancement and the conditions associated with it.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1016/j.foreco.2023.121356">Henry and Walters (2023), Michigan age structure</a></td>
<td>Small-diameter maples can be old, suppressed stems. Sapling presence alone is not evidence of recent establishment; the paper’s size classes differ from FIA’s.</td>
</tr>
<tr class="odd">
<td><a href="https://research.fs.usda.gov/treesearch/67377">Harris et al.&nbsp;(2022), seedling inventories and sapling recruitment</a></td>
<td>This directly relevant prior study already predicts FIA recruitment and compares ordinary tallies with six height classes. Taller seedlings were more informative. A Michigan analysis must acknowledge that precedent.</td>
</tr>
<tr class="even">
<td><a href="https://research.fs.usda.gov/treesearch/69473">Harris et al.&nbsp;(2025), browsing by size class</a></td>
<td>Browse relationships vary with regeneration size. A single coarse seedling tally loses information. Mechanism claims require independent browse measurements.</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1002/ece3.71386">Gauthier (2025), Canadian maple and beech saplings</a></td>
<td>Beech is a candidate explanation. Different geography, diameter definitions, and the use of relative abundance limit direct transfer to Michigan seedling loss.</td>
</tr>
<tr class="even">
<td><a href="https://research.fs.usda.gov/treesearch/81033">Harris et al.&nbsp;(2026), regional regeneration trends</a></td>
<td>Small seedlings and sapling abundance can imply different future forest composition. The mismatch is a useful research problem.</td>
</tr>
<tr class="odd">
<td><a href="https://research.fs.usda.gov/treesearch/81034">Harris et al.&nbsp;(2026), regeneration after disturbance</a></td>
<td>Advance-regeneration forecasting after disturbance is also established work. A generic harvest or longitudinal model is not an unoccupied research niche.</td>
</tr>
</tbody>
</table>
<p>The FIA Regeneration Indicator is a possible companion dataset. Before using its browse-impact score, check its construction: scarcity of regeneration can enter the assessment, creating circularity if the same scarcity is modeled as the response. Height, diameter, and age thresholds are not interchangeable.</p>
</section>
<section id="initial-feasibility-screen-before-the-endpoint-audit" class="level2">
<h2 class="anchored" data-anchor-id="initial-feasibility-screen-before-the-endpoint-audit">Initial feasibility screen, before the endpoint audit</h2>
<p>The following are exploratory record counts, not survey-weighted estimates or final recruitment-cohort results. Reproduce them with <a href="../scripts/12_audit_recruitment_feasibility.R"><code>scripts/12_audit_recruitment_feasibility.R</code></a>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Candidate analysis in the existing 932 pairs</th>
<th>Initial support</th>
<th>Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Newly recorded live maple saplings, 1 to &lt;5 inches DBH, with <code>RECONCILECD=1</code> and no predecessor TREE record</td>
<td>171 stems in 101 conditions, across 23 counties</td>
<td>Candidate screen; subsequent protocol and frame checks retain 169 stems in 100 conditions.</td>
</tr>
<tr class="even">
<td>Follow tagged baseline maple saplings</td>
<td>1,593 stems in 573 conditions; 1,255 followed as alive, 337 dead, one cruiser-error record</td>
<td>Useful companion for survival and growth; audit species reidentification and sampling-frame exit.</td>
</tr>
<tr class="odd">
<td>Sapling detection newly appearing where no saplings were detected at baseline</td>
<td>14 of 359 conditions</td>
<td>Too sparse to organize a broad predictor model around this restriction.</td>
</tr>
<tr class="even">
<td>Existing seedling-detection loss</td>
<td>75 of 677 baseline detections</td>
<td>Retain as an observation-process comparison.</td>
</tr>
</tbody>
</table>
<p>All 101 recruit-bearing conditions in the current-pair screen had seedlings at baseline. The 255 baseline non-detections had no qualifying recruits in this screen; this does not establish zero underlying probability. A conditional analysis among the 677 baseline detections is feasible, while an all-condition model needs an explicit approach to separation and uncertainty.</p>
<p>Fifty-nine linked live baseline saplings crossed 5 inches DBH. Of 76 conditions with a corrected later absence of maple saplings, 15 contained such larger survivors. Sapling disappearance therefore cannot be assigned wholesale to mortality. Three living stems were reidentified as red maple, and one fully sampled, zero-live-tree follow-up had missing derived sapling metrics; its zero must be reconciled from the source records before a new endpoint is built.</p>
<p>Historical screening identifies 2,308 candidate condition intervals on 1,102 physical plots. There are 345 new live sapling tallies in 230 intervals across 180 plots and 32 counties. Follow-ups span 2009–2025. These intervals reuse physical plots and are not independent observations. The final cohort must check protocols, actual measurement dates, shared area, predecessors, old forest-type codes, and repeated conditions before its size is fixed. In particular, 110 intervals fall outside the pilot’s 4.5–8.5-year bounds.</p>
</section>
<section id="questions-and-completion-criteria" class="level2">
<h2 class="anchored" data-anchor-id="questions-and-completion-criteria">Questions and completion criteria</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Priority</th>
<th>Question</th>
<th>What counts as completion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Define the outcome</td>
<td>Which new TREE tallies represent recruitment into the sapling class on comparable sampled area?</td>
<td>An audited recruitment table, exclusion flow, protocol definitions, and source checks for ingrowth, missed trees, changed area, and species corrections.</td>
</tr>
<tr class="even">
<td>2. Test information value</td>
<td>How much do seedling abundance and sapling structure improve recruitment prediction beyond observation opportunity and existing stocking?</td>
<td>Identical held-out records for a small declared sequence of models; paired Brier differences, calibration, AUC, and uncertainty reported for every comparison.</td>
</tr>
<tr class="odd">
<td>3. Explain size-class change</td>
<td>How much sapling disappearance represents death, surviving growth into a larger class, or record changes?</td>
<td>A linked-stem fate table with denominators and ambiguous records retained separately; growth summaries limited to valid comparable measurements.</td>
</tr>
<tr class="even">
<td>4. Evaluate usefulness</td>
<td>Are ordinary regeneration indicators adequate for identifying conditions that warrant a more detailed survey?</td>
<td>A declared survey objective and capacity, comparison with a simple abundance rule, and validation that matches the intended use. Until then, no operational triage claim.</td>
</tr>
</tbody>
</table>
<p>The implemented analysis follows a small benchmark sequence: observation coverage and interval; then starting seedling abundance; then existing maple sapling structure and established-maple abundance. Both the full cohort and the baseline-detected subgroup are principal analyses. Fixed ridge shrinkage, paired full-refit county resampling, exact-frame and protocol sensitivities, and a retrospective temporal split are documented in the <a href="../research/runs/recruitment-2026-09-08/analysis-contract.md">analysis contract</a>. No competitor or beech term was added after observing the results.</p>
<p>Goals 1–3 are complete for the bounded Michigan study, subject to its stated measurement and internal-validation limits. The revised paper integrates their results and uncertainty. Goal 4 has an explicit proxy target and fixed-capacity comparisons with simple rules. It remains open operationally: survey need, costs, and external usefulness have not been established. That separate requirement does not block the core measurement-and-prediction paper.</p>
<p>For historical intervals, declare later measurements for temporal assessment before comparing models. Separately assess transfer to unseen counties or plots; a later visit to a known plot answers a different question from a new location. Keep every physical plot together for geographic validation, account for reused plots in uncertainty, and report the sample’s geographic support. Because the current outcomes have already been examined, describe a temporal split of this snapshot as a retrospective robustness check, not untouched external validation.</p>
</section>
<section id="scope-and-stopping-rules" class="level2">
<h2 class="anchored" data-anchor-id="scope-and-stopping-rules">Scope and stopping rules</h2>
<ul>
<li>Start with the existing Michigan database and common FIA measurements. Wisconsin/Minnesota feasibility acquisition is now authorized. Additional geographies, new environmental joins, and fieldwork remain separate decisions.</li>
<li>Do not equate the first 1-inch TREE tally with a tagged seedling’s survival, seed origin, age, or eventual canopy recruitment. New large subplot tallies can arise from the change in sampled area at 5 inches.</li>
<li>Analyze invalid or changed observation opportunities separately from biological outcomes. Inspect exact-overlap and comparable-protocol sensitivities before interpreting recruitment differences.</li>
<li>Publish an imprecise or negative result if added variables fail to improve the strong benchmark. Do not keep adding covariates until a preferred story wins.</li>
<li>If recruitment support or linkage quality becomes inadequate, report a descriptive recruitment/fate audit and measurement limits. Do not substitute an easier endpoint while keeping the same ecological claim.</li>
<li>Keep mechanism and treatment claims as hypotheses. A causal intervention study requires a different design.</li>
</ul>
</section>
<section id="status-and-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="status-and-reproducibility">Status and reproducibility</h2>
<p>The existing detection models are exploratory pilot results. The direction review, endpoint rebuild, first recruitment models, and linked-fate accounting are complete locally. Operational usefulness and external validation remain unresolved. No new publication or deployment is implied.</p>
<p>The survey-priority extension and RI record-availability screen are also complete locally. Run <code>make survey-audit</code> after the recruitment models exist. The <a href="../outputs/tables/recruitment-survey-summary.csv">capacity results</a>, <a href="../outputs/tables/recruitment-survey-paired-differences.csv">paired differences</a>, and <a href="../outputs/tables/recruitment-survey-ri-coverage.csv">RI availability</a> document that extension. The subsequent <a href="../report/ri-audit.html">RI measurement audit</a> is complete with historical-source qualifications; run <code>make ri-audit</code> after the recruitment dataset exists. Length information’s added forecasting value and its usefulness for an actual survey decision remain untested.</p>
<p>Run <code>make recruitment</code>, <code>make test</code>, and <code>make report</code> after the longitudinal artifacts exist to regenerate and check the new analysis. The <a href="../research/README.md">research vault</a> records the HyperResearch-inspired method, source access, analysis contract, and review trail. This is a local adaptation, not execution of HyperResearch’s native harness.</p>
<p>Run <code>make direction-audit</code> after the longitudinal artifacts exist to regenerate the comparison and feasibility evidence. The incremental prediction audit reuses the pilot’s county folds. Any bootstrap intervals from its saved predictions are conditional on those fitted folds and omit model-development and fold-selection uncertainty.</p>
<p>The aggregate <a href="../outputs/audits/research-direction-model-summary.csv">benchmark comparison</a>, <a href="../outputs/audits/research-direction-conditional-bootstrap.csv">conditional uncertainty</a>, <a href="../outputs/audits/recruitment-feasibility-current-summary.csv">current recruitment feasibility</a>, and <a href="../outputs/audits/recruitment-feasibility-historical-summary.csv">historical feasibility</a> provide the numerical evidence behind this decision.</p>
<p>Earlier v2.0 release checks document successful software execution and numerical reconciliation. They do not establish that the earlier research interpretation was sufficiently supported. This direction document supersedes that interpretation.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dineshpotla\.github\.io\/canopy-to-cohort\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Research direction and goals"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-09"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## Decision</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>The bounded Michigan core research is complete as of September 9, 2026. The</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">revised paper</span><span class="co">](../report/recruitment.qmd)</span> answers the count-information,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>incremental-stage, and linked-fate questions. Regional data acquisition and</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>length-model validation are deferred optional extensions, not prerequisites</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>for completing this paper. The results do not justify another pivot merely</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>because added-model improvements are small or uncertain.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>Change the primary question to **whether observed sugar-maple regeneration leads</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>to recorded recruitment into the sapling size class**. Retain the existing</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>seedling-detection analysis as an exploratory measurement study. Its numerical</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>results remain useful, but the earlier claim that it establishes a field-triage</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>tool is withdrawn.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>The project's goal is:</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Determine how well ordinary FIA seedling and sapling observations anticipate</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; new sugar-maple sapling recruitment in Michigan northern hardwoods, measure</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; what additional stand information contributes, and distinguish recruitment,</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; survival, growth, and observation changes.</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>The intended contribution is a transparent Michigan evaluation of regeneration</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>indicators. Its novelty must come from a useful comparison and credible</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>validation. Linking repeated FIA visits or fitting a prediction model is already</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>established in the literature.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>The direction decision was made on September 7. The first recruitment analysis</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>was implemented on September 8; its results are summarized below and in the</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">recruitment report</span><span class="co">](../report/recruitment.qmd)</span>. The existing data have been</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>explored; this is not a preregistration or external validation.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results after implementing the pivot</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>The final audited recruitment cohort has 922 condition intervals on 903 physical</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>plots across 66 counties. It contains 169 qualifying new live maple saplings in</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>100 conditions. Nine source pairs fail the conservative shared-frame proportion</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>check and one contains ambiguous new sapling records. The preliminary feasibility</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>counts later in this document are preserved as the earlier screen, not final results.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>Seedling count plus coverage and interval has county-held-out AUC 0.796 overall</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>and 0.699 among 672 baseline-detected conditions. Adding existing maple sapling</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>density and established-maple basal area yields AUC 0.806 and 0.711, respectively.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>The paired Brier improvements are about 0.0016 in both populations, with full-refit</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>county-bootstrap intervals spanning zero. At equal top-quarter capacity the</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>stage model captures fewer recruit-bearing conditions than the count benchmark.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>These findings do not support organizing the project around added model complexity.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Counts nevertheless contain information. Of 280 conditions with more than twenty</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>recorded baseline seedlings, 72 have a qualifying new sapling at follow-up.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Abundant seedlings therefore do not guarantee recorded entry, but the remaining</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>208 conditions cannot be labeled biological failures from these observations.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>The companion fate audit separates 334 recorded deaths, 1,188 surviving saplings,</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>and 58 live stems advancing beyond the sapling class among 1,580 comparable stems.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>The central contribution is now an implemented measurement-and-prediction study:</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>**what standard regeneration counts tell us, what maple stage variables add,</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>and what neither observation establishes about successful cohort replacement.**</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>Continue with a defined decision and external assessment if operational use is</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>the goal. Do not pivot again merely because incremental effects are modest.</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="fu">## Secondary survey comparison and optional next goal</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>An explicit, retrospective priority comparison is now implemented. Its main</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>target is no recorded entry among the 672 baseline-detected conditions, at a</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>fixed 25% capacity. Expected target capture is 143 for random selection,</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>162 for low raw counts, 160 for the count model, and 163 for the stage model.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Stage minus raw-count yield is +0.60 percentage points (95% full-refit county</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>interval −3.66 to +2.28). This is not a demonstrated practical improvement.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>The later-year test gives 65.18 expected targets for raw counts versus 65 for</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>either model, among 68 selected conditions.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>The extension also tests the opposite objective, fixed 10%/50% capacities,</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>cutoff-tie uncertainty, and a common seven-year scoring horizon. No-entry</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>remains a record-based proxy, not an independent finding that a site needs</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>surveying. Actual field costs and useful survey outcomes remain unmeasured.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>The measurement audit has sharpened an optional follow-on hypothesis:</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Determine whether baseline seedling length structure adds useful recruitment</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; information beyond ordinary counts on the same sampled area, evaluated on a</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; separate and adequately supported sample.</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">RI audit</span><span class="co">](../report/ri-audit.qmd)</span> retains 90 baseline condition intervals,</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>14 events, and 311 sampled microplot-condition intervals. Ordinary maple counts</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>exactly equal the sum of RI classes at least one foot long on every matched</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>unit; length distribution, not the collapsed total, is the candidate extra</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>information. Thirteen of the fourteen events occur in the 44 conditions with</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>baseline maple seedlings at least five feet long, versus one event in 46</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>conditions without them. This is not an adjusted or held-out count-versus-length</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>comparison.</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>No height-class model is fitted. The later-year split would leave ten development</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>events and four assessment events. Historical annual supplements were inspected</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>for 2016-2018 (37 intervals, four events), including an archived 2016 draft,</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>but not individually recovered for 2012-2015. The baseline measurement audit</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>is complete with those qualifications;</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>independent forecasting usefulness is not established.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">survey validation plan</span><span class="co">](survey-validation-plan.md)</span> records this milestone,</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>the next matched comparison, and the independent decision evidence required before</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>an operational claim. Earlier Wisconsin/Minnesota acquisition was authorized,</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>but that extension is now deferred to prioritize the core paper. Broader</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>extensions and fieldwork remain separate scope decisions.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="fu">## Count-versus-length design</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>The optional comparison is specified in the <span class="co">[</span><span class="ot">study design</span><span class="co">](../report/length-study.qmd)</span>:</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>ordinary count, sampling coverage, and elapsed interval versus the same model</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>plus the fraction of standard-size seedlings at least five feet long. The</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>primary population has ordinary seedlings detected, and the primary metric is</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>plot-balanced paired Brier gain. This is a conditional next-visit comparison,</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>not a validated baseline forecast at an exact seven-year horizon.</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>The metadata-only historical screen finds 88 positive-seedling opportunities</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>on 79 physical plots, before full RI/condition/endpoint checks. Only seven visits</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>on six plots are outside the current 903-plot recruitment cohort. No new</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>recruitment outcomes were extracted. That small extension does not supply an</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>independent Michigan evaluation set.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>The protocol includes hypothetical precision scenarios and a gate requiring</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>a minimum meaningful gain before evaluation; it does not invent field costs</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>or claim that one sample-size rule suffices. The user has authorized the</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>Wisconsin/Minnesota feasibility screen under the same definitions. Such an</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>extension would assess regional transport, not validate Michigan-specific</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>performance. Both archive downloads currently fail with empty responses, so no</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>new state inventory was acquired and regional sample support remains unknown.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">access review</span><span class="co">](../research/runs/recruitment-2026-09-08/regional-access-review.md)</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>records the blocker and reproducible retry step.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why the previous direction needs revision</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**The outcome was too far from the ecological problem.** A positive seedling</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>   tally becoming zero measures a change in a sampled size class. It can reflect</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>   mortality, sampling variation, or growth out of that class. Continued seedling</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>   presence can coexist with little recruitment into larger trees. The pilot</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>   therefore does not directly establish regeneration failure or recovery.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Most prediction gain was already available from a simple benchmark.** In</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>   the existing county-held-out results, density + coverage + interval achieved</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>   AUC 0.8447 and Brier 0.08253. The full seven-slope model achieved 0.8557 and</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>   0.08151. The simpler benchmark accounts for 94.2% of the full model's Brier</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>   improvement over prevalence. Added stand variables reduced benchmark Brier</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>   by only 1.24%. Whether that difference is useful requires uncertainty and a</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>   defined decision, not just the headline AUC. A paired county bootstrap of</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>   existing held-out predictions gives a Brier difference of −0.00102 with a</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>   95% interval of −0.00585 to +0.00475 (negative favors the full model). This</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>   conditional interval includes zero; it does not prove equivalence. At equal</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>   capacity of 169 conditions, the full model captures 55 losses versus 53 for</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>   the strong benchmark. Sixty of 75 losses began with five or fewer tallied</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>   seedlings, directly reconciled against <span class="in">`SEEDLING.TREECOUNT`</span>.</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**The beech story was promoted too early.** A conditional association is worth</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>   investigating, but its modest incremental prediction does not establish an</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>   actionable mechanism. The old stage comparator excludes beech sapling basal</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>   area from its competitor total. A fair species-specific check also needs a</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>   model with total non-maple basal area, then asks what beech adds. That audit</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>   leaves full-model performance almost unchanged: it does not erase the beech</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>   association, but incremental uncertainty remains substantial.</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**A weak small model does not establish a limit of the whole database.** The</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>   four-term appearance model performed poorly. That result concerns the tested</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>   model, cohort, and validation partition; it does not show that no FIA-based</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>   method can predict new detections.</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Passing software checks did not settle the research question.** Ten events</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>   per slope is a rough accounting statistic, not a guarantee of reliable</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>   prediction. Sample-size planning also depends on outcome frequency, candidate</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>   complexity, clustering, and expected model performance. See</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>   <span class="co">[</span><span class="ot">Riley et al. (2020)</span><span class="co">](https://doi.org/10.1136/bmj.m441)</span>. Tests should reproduce</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>   calculations; they should not require the appearance model to remain weak.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the relevant research actually supports</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Primary source <span class="pp">|</span> Consequence for this project <span class="pp">|</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Henry et al. (2021), Michigan regeneration</span><span class="co">](https://doi.org/10.1016/j.foreco.2020.118541)</span> <span class="pp">|</span> Small seedlings can be plentiful while larger regeneration is scarce. Study advancement and the conditions associated with it. <span class="pp">|</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Henry and Walters (2023), Michigan age structure</span><span class="co">](https://doi.org/10.1016/j.foreco.2023.121356)</span> <span class="pp">|</span> Small-diameter maples can be old, suppressed stems. Sapling presence alone is not evidence of recent establishment; the paper's size classes differ from FIA's. <span class="pp">|</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Harris et al. (2022), seedling inventories and sapling recruitment</span><span class="co">](https://research.fs.usda.gov/treesearch/67377)</span> <span class="pp">|</span> This directly relevant prior study already predicts FIA recruitment and compares ordinary tallies with six height classes. Taller seedlings were more informative. A Michigan analysis must acknowledge that precedent. <span class="pp">|</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Harris et al. (2025), browsing by size class</span><span class="co">](https://research.fs.usda.gov/treesearch/69473)</span> <span class="pp">|</span> Browse relationships vary with regeneration size. A single coarse seedling tally loses information. Mechanism claims require independent browse measurements. <span class="pp">|</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Gauthier (2025), Canadian maple and beech saplings</span><span class="co">](https://doi.org/10.1002/ece3.71386)</span> <span class="pp">|</span> Beech is a candidate explanation. Different geography, diameter definitions, and the use of relative abundance limit direct transfer to Michigan seedling loss. <span class="pp">|</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Harris et al. (2026), regional regeneration trends</span><span class="co">](https://research.fs.usda.gov/treesearch/81033)</span> <span class="pp">|</span> Small seedlings and sapling abundance can imply different future forest composition. The mismatch is a useful research problem. <span class="pp">|</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Harris et al. (2026), regeneration after disturbance</span><span class="co">](https://research.fs.usda.gov/treesearch/81034)</span> <span class="pp">|</span> Advance-regeneration forecasting after disturbance is also established work. A generic harvest or longitudinal model is not an unoccupied research niche. <span class="pp">|</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>The FIA Regeneration Indicator is a possible companion dataset. Before using its</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>browse-impact score, check its construction: scarcity of regeneration can enter</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>the assessment, creating circularity if the same scarcity is modeled as the</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>response. Height, diameter, and age thresholds are not interchangeable.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="fu">## Initial feasibility screen, before the endpoint audit</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>The following are exploratory record counts, not survey-weighted estimates or</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>final recruitment-cohort results. Reproduce them with</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`scripts/12_audit_recruitment_feasibility.R`</span><span class="co">](../scripts/12_audit_recruitment_feasibility.R)</span>.</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Candidate analysis in the existing 932 pairs <span class="pp">|</span> Initial support <span class="pp">|</span> Decision <span class="pp">|</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Newly recorded live maple saplings, 1 to &lt;5 inches DBH, with <span class="in">`RECONCILECD=1`</span> and no predecessor TREE record <span class="pp">|</span> 171 stems in 101 conditions, across 23 counties <span class="pp">|</span> Candidate screen; subsequent protocol and frame checks retain 169 stems in 100 conditions. <span class="pp">|</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Follow tagged baseline maple saplings <span class="pp">|</span> 1,593 stems in 573 conditions; 1,255 followed as alive, 337 dead, one cruiser-error record <span class="pp">|</span> Useful companion for survival and growth; audit species reidentification and sampling-frame exit. <span class="pp">|</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sapling detection newly appearing where no saplings were detected at baseline <span class="pp">|</span> 14 of 359 conditions <span class="pp">|</span> Too sparse to organize a broad predictor model around this restriction. <span class="pp">|</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Existing seedling-detection loss <span class="pp">|</span> 75 of 677 baseline detections <span class="pp">|</span> Retain as an observation-process comparison. <span class="pp">|</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>All 101 recruit-bearing conditions in the current-pair screen had seedlings at</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>baseline. The 255 baseline non-detections had no qualifying recruits in this</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>screen; this does not establish zero underlying probability. A conditional</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>analysis among the 677 baseline detections is feasible, while an all-condition</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>model needs an explicit approach to separation and uncertainty.</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>Fifty-nine linked live baseline saplings crossed 5 inches DBH. Of 76 conditions</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>with a corrected later absence of maple saplings, 15 contained such larger</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>survivors. Sapling disappearance therefore cannot be assigned wholesale to</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>mortality. Three living stems were reidentified as red maple, and one fully</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>sampled, zero-live-tree follow-up had missing derived sapling metrics; its zero</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>must be reconciled from the source records before a new endpoint is built.</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>Historical screening identifies 2,308 candidate condition intervals on 1,102</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>physical plots. There are 345 new live sapling tallies in 230 intervals across</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>180 plots and 32 counties. Follow-ups span 2009–2025. These intervals reuse</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>physical plots and are not independent observations. The final cohort must</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>check protocols, actual measurement dates, shared area, predecessors, old</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>forest-type codes, and repeated conditions before its size is fixed. In</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>particular, 110 intervals fall outside the pilot's 4.5–8.5-year bounds.</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questions and completion criteria</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Priority <span class="pp">|</span> Question <span class="pp">|</span> What counts as completion <span class="pp">|</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1. Define the outcome <span class="pp">|</span> Which new TREE tallies represent recruitment into the sapling class on comparable sampled area? <span class="pp">|</span> An audited recruitment table, exclusion flow, protocol definitions, and source checks for ingrowth, missed trees, changed area, and species corrections. <span class="pp">|</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2. Test information value <span class="pp">|</span> How much do seedling abundance and sapling structure improve recruitment prediction beyond observation opportunity and existing stocking? <span class="pp">|</span> Identical held-out records for a small declared sequence of models; paired Brier differences, calibration, AUC, and uncertainty reported for every comparison. <span class="pp">|</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3. Explain size-class change <span class="pp">|</span> How much sapling disappearance represents death, surviving growth into a larger class, or record changes? <span class="pp">|</span> A linked-stem fate table with denominators and ambiguous records retained separately; growth summaries limited to valid comparable measurements. <span class="pp">|</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4. Evaluate usefulness <span class="pp">|</span> Are ordinary regeneration indicators adequate for identifying conditions that warrant a more detailed survey? <span class="pp">|</span> A declared survey objective and capacity, comparison with a simple abundance rule, and validation that matches the intended use. Until then, no operational triage claim. <span class="pp">|</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>The implemented analysis follows a small benchmark sequence: observation</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>coverage and interval; then starting seedling abundance; then existing maple</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>sapling structure and established-maple abundance. Both the full cohort and the</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>baseline-detected subgroup are principal analyses. Fixed ridge shrinkage, paired</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>full-refit county resampling, exact-frame and protocol sensitivities, and a</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>retrospective temporal split are documented in the</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">analysis contract</span><span class="co">](../research/runs/recruitment-2026-09-08/analysis-contract.md)</span>.</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>No competitor or beech term was added after observing the results.</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>Goals 1–3 are complete for the bounded Michigan study, subject to its stated</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>measurement and internal-validation limits. The revised paper integrates</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>their results and uncertainty. Goal 4 has an explicit proxy target and</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>fixed-capacity comparisons with simple rules. It remains open operationally:</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>survey need, costs, and external usefulness have not been established. That</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>separate requirement does not block the core measurement-and-prediction paper.</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>For historical intervals, declare later measurements for temporal assessment</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>before comparing models. Separately assess transfer to unseen counties or plots;</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>a later visit to a known plot answers a different question from a new location.</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>Keep every physical plot together for geographic validation, account for reused</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>plots in uncertainty, and report the sample's geographic support. Because the</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>current outcomes have already been examined, describe a temporal split of this</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>snapshot as a retrospective robustness check, not untouched external validation.</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scope and stopping rules</span></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Start with the existing Michigan database and common FIA measurements.</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>  Wisconsin/Minnesota feasibility acquisition is now authorized. Additional</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>  geographies, new environmental joins, and fieldwork remain separate decisions.</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Do not equate the first 1-inch TREE tally with a tagged seedling's survival,</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>  seed origin, age, or eventual canopy recruitment. New large subplot tallies</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>  can arise from the change in sampled area at 5 inches.</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Analyze invalid or changed observation opportunities separately from</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>  biological outcomes. Inspect exact-overlap and comparable-protocol</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>  sensitivities before interpreting recruitment differences.</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Publish an imprecise or negative result if added variables fail to improve the</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>  strong benchmark. Do not keep adding covariates until a preferred story wins.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>If recruitment support or linkage quality becomes inadequate, report a</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>  descriptive recruitment/fate audit and measurement limits. Do not substitute</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>  an easier endpoint while keeping the same ecological claim.</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Keep mechanism and treatment claims as hypotheses. A causal intervention</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>  study requires a different design.</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="fu">## Status and reproducibility</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>The existing detection models are exploratory pilot results. The direction</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>review, endpoint rebuild, first recruitment models, and linked-fate accounting</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>are complete locally. Operational usefulness and external validation remain</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>unresolved. No new publication or deployment is implied.</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>The survey-priority extension and RI record-availability screen are also</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>complete locally. Run <span class="in">`make survey-audit`</span> after the recruitment models exist.</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">capacity results</span><span class="co">](../outputs/tables/recruitment-survey-summary.csv)</span>,</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">paired differences</span><span class="co">](../outputs/tables/recruitment-survey-paired-differences.csv)</span>,</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>and <span class="co">[</span><span class="ot">RI availability</span><span class="co">](../outputs/tables/recruitment-survey-ri-coverage.csv)</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>document that extension. The subsequent <span class="co">[</span><span class="ot">RI measurement audit</span><span class="co">](../report/ri-audit.qmd)</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>is complete with historical-source qualifications; run <span class="in">`make ri-audit`</span> after</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>the recruitment dataset exists. Length information's added forecasting value</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>and its usefulness for an actual survey decision remain untested.</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>Run <span class="in">`make recruitment`</span>, <span class="in">`make test`</span>, and <span class="in">`make report`</span> after the longitudinal</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>artifacts exist to regenerate and check the new analysis. The</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">research vault</span><span class="co">](../research/README.md)</span> records the HyperResearch-inspired method,</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>source access, analysis contract, and review trail. This is a local adaptation,</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>not execution of HyperResearch's native harness.</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>Run <span class="in">`make direction-audit`</span> after the longitudinal artifacts exist to regenerate</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>the comparison and feasibility evidence. The incremental prediction audit</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>reuses the pilot's county folds. Any bootstrap intervals from its saved</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>predictions are conditional on those fitted folds and omit model-development</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>and fold-selection uncertainty.</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>The aggregate <span class="co">[</span><span class="ot">benchmark comparison</span><span class="co">](../outputs/audits/research-direction-model-summary.csv)</span>,</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">conditional uncertainty</span><span class="co">](../outputs/audits/research-direction-conditional-bootstrap.csv)</span>,</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">current recruitment feasibility</span><span class="co">](../outputs/audits/recruitment-feasibility-current-summary.csv)</span>,</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a>and <span class="co">[</span><span class="ot">historical feasibility</span><span class="co">](../outputs/audits/recruitment-feasibility-historical-summary.csv)</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>provide the numerical evidence behind this decision.</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>Earlier v2.0 release checks document successful software execution and numerical</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>reconciliation. They do not establish that the earlier research interpretation</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a>was sufficiently supported. This direction document supersedes that interpretation.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dineshpotla/canopy-to-cohort/blob/main/docs/research-direction.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/dineshpotla/canopy-to-cohort/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>